### ISSUE TITLE
Can't properly render images with exif data

### ISSUE THREAD

**Issue by 4leyam** [SDWebImage/SDWebImageSwiftUI#101]
hello, first of all thank you guys for this useful library, my problem here is that i'm having an issue to correctly display an 2700x2160 image containing exif data (orientation) on a real device (iPhone 7) the following is the code that i'm using

`WebImage(url: URL(string: "https://dv6mh24acw2xi.cloudfront.net/public/moments/gabbr/tmpImg9143171451882065582.jpeg" )).resizable().placeholder {
                               Rectangle().fill(Color(UIColor.systemBackground)).overlay(Text("loading..."))
}.scaledToFit()`

i don't know if i'm the one doing it wrong or if there is actually a problem
thanks for your help.

**Comment by dreampiggy** [comment]
You’re not doing wrong. It indeed a SwiftUI bug. You can not render it correctly with SwiftUI.Image via a UIImage initializer either.

See more: https://github.com/onevcat/Kingfisher/issues/1395

We can provide a fix, but it’s complicated compared to Kingfisher. The loaded image can be subclass of UIImage, or can contains vector image data, both of cases that Kingfisher’s normalized method does not handle. Which will cause nww issues.

If you really want our framework, to handle a bug that SwiftUI team itself cause, I can do some protect by rendered the loaded image with a dummy CGImage based instead. But I doubt this will cause more RAM usage even for normal non-EXIF images.

**Comment by dreampiggy** [comment]
Actually, WebInage is a struct `If SwiftUI.Image works, it works. But if SwiftUI.Image not works, it may not works either` 😼

**Comment by dreampiggy** [comment]
@4leyam I found the `Image(decorative: cgImage, scale: image.scale, orientation: orientation)` actually works for EXIF image and `aspectRatio` modifier.

![image](https://user-images.githubusercontent.com/6919743/79298610-35fbf680-7f14-11ea-9d72-5c8379398456.png)


For vector images, I decide to handle this suck in framework itself. If you load PDF/SVG vector images on `WebImage`, it will automatically generate a bitmap with the PDF/SVG default size(may be small than your rendering ImageView's size), at least you don't need previous version's hack code from user side:

https://github.com/SDWebImage/SDWebImageSwiftUI/blob/1.3.2/Example/SDWebImageSwiftUIDemo/AppDelegate.swift#L33-L36

**Comment by dreampiggy** [comment]
Hack, but works :).  Good SwiftUI

For this EXIF images, the hack does not have any performance cost compared to Kingfisher's normalized logic (Which will create a bitmap context in main queue and block). Good SwiftUI

![image](https://user-images.githubusercontent.com/6919743/79298653-5461f200-7f14-11ea-99c6-85f7740614a3.png)

**Comment by dreampiggy** [comment]
[1.3.3](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/1.3.3) version released, which fix the cases for EXIF (5-8) images rendering issue on `WebImage`. Also render the vector images as bitmap by default (previously will show empty)

**Comment by 4leyam** [comment]
hey, sorry for the late reply, and thank you for your help and quick reply, it's correctly working now once again thanks
