### ISSUE TITLE
save image to PhotosAlbum

### ISSUE THREAD

**Issue by AttemptD** [SDWebImage/SDWebImageSwiftUI#104]
I use webImage,but I also want to keep it in PhotosAlbum,I don‘t know how to save it

**Comment by dreampiggy** [comment]
Seems you need to disable the Disk Cache Query, then use PhotosKit API to write it into Photos Album.

Demo code:

```swift
imageView.sd_setImage(with: url, context: [.storeCacheType: SDImageCacheType.disk.rawValue]) { image, data, cacheType, url
    guard let data = data else { return }
    let request = PHAssetCreationRequest.forAsset()
    request.addResource(with: .photo, data: data, nil)
}
```

**Comment by AttemptD** [comment]
@dreampiggy Thanks I've solved

**Comment by dreampiggy** [comment]
How do you solve this ? Directly call the `SDWebImage` to load image and data ?

This Data arg and any other information will be available in version 2.0.0, which is a major version.

**Comment by dreampiggy** [comment]
@AttemptD Because of API stable, I can not break current `onSuccess` modifier.

But from v1.4.0, the `ImageManager` class provide the `imageData`, which is a obserable object. You can use `@Observed` to receive the `imageData` load finished callback, then store it into the Photos Album.

**Comment by dreampiggy** [comment]
@AttemptD 

By using the overload method, [v1.4.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/1.4.0) supports the image data arg. You can use `.onSuccess { image, data, cacheType in }` to grab the possible downloaded  data and save it to Photos Album.

**Comment by h-elbeheiry** [comment]
@dreampiggy @AttemptD I'm trying to implement the same feature, I have SDWebImage and was trying to have a button to allow the user to save the image to Photos, but can't seem to find any tutorial that works with SwiftUI + URL Images 😓 Can you guys help me with snippet of code in SwiftUI , Thanks in advance
