### ISSUE TITLE
Errors when using WebImage

### ISSUE THREAD

**Issue by Veeit** [SDWebImage/SDWebImageSwiftUI#108]
I updated my version from this framework today. Now I get all over the place error messages.

"'WebImage' cannot be constructed because it has no accessible initializers"
"Type 'Any' has no member 'decodeFirstFrameOnly'"
"Type 'AnyHashable' has no member 'imageThumbnailPixelSize'"
"Cannot infer contextual base in reference to member 'fit'"

<img width="1034" alt="Screenshot 2020-05-06 at 12 47 06" src="https://user-images.githubusercontent.com/22853176/81168782-f3b85900-8f97-11ea-973c-f5497227df2f.png">

**Comment by dreampiggy** [comment]
Seems you forgot to `import SDWebImage` firstly.

This is no longer needed after [v1.3.2](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/1.3.2)

**Comment by Veeit** [comment]
clean the build helped :)
