### ISSUE TITLE
Could not connect to the server

### ISSUE THREAD

**Issue by zdhgithub** [SDWebImage/SDWebImageSwiftUI#110]
当加载github上的图片时报错，请问如何处理？

Task <8E3F20E6-71F8-4112-ABE9-6285E8F43626>.<1> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x2838672a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <8E3F20E6-71F8-4112-ABE9-6285E8F43626>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <8E3F20E6-71F8-4112-ABE9-6285E8F43626>.<1>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif, NSErrorFailingURLKey=https://raw.githubusercontent.com/liyong03/YLGIFImage/master/YLGIFImageDemo/YLGIFImageDemo/joy.gif, _kCFStreamErrorDomainKey=1}

**Comment by dreampiggy** [comment]
Can not reproduce.

This seems the network issue, are you using Proxy ?

**Comment by dreampiggy** [comment]
Github S3 is block by ISPs in China Mainland, make sure you use the Proxy or other mirror CDNs.
