### ISSUE TITLE
Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by yixe** [SDWebImage/SDWebImageSwiftUI#112]
Hello, I'm getting this odd crash and in the load function specifically it points at line 63: self.isLoading = true

console: "cycle detected through attribute 7348 ==="
precondition failure: invalid input index: 0

any ideas?

**Comment by dreampiggy** [comment]
@yixe  Seems...Not able to debug based on this information.

Anything extra information, like full stacktrace ?
