### ISSUE TITLE
Image transition requires indicator

### ISSUE THREAD

**Issue by yonaskolb** [SDWebImage/SDWebImageSwiftUI#115]
It seems image loaded transitions require an indicator to be set if even if one isn't required

Animation works:
```swift
WebImage(url: url)
    .renderingMode(.original)
    .resizable()
    .placeholder {
        Asset.avatar.image
        .resizable()
        .renderingMode(.original)
    }
    .indicator(Indicator { _, _ in EmptyView()}) // or .indicator(.activity)
    .animation(.easeInOut(duration: 0.2))
    .transition(.fade)
```

No animations occur:
```swift
WebImage(url: url)
    .renderingMode(.original)
    .resizable()
    .placeholder {
        Asset.avatar.image
        .resizable()
        .renderingMode(.original)
    }
    .animation(.easeInOut(duration: 0.2))
    .transition(.fade)
```

**Comment by dreampiggy** [comment]
Seems this bug only applies for `WebImage`. The `AnimatedImage` transition works without any indicator required.

**Comment by dreampiggy** [comment]
Seems this bug only relatede to the `.fade` convenient method.

You can try to use the following to workaround. Looks like a bug in SwiftUI from iOS 13.2+. iOS 13.0 does not have this strange behavior.

```swift
WebImage(url: url)
.transition(.asymmetric(insertion: AnyTransition.opacity.animation(.easeInOut(duration: 0.5)), removal: AnyTransition.identity))
```

**Comment by dreampiggy** [comment]
I've release v1.4.1 to introduce this new API. Until Apple fix this issue, you'd better use that `.fade(duration:)` API instead, or create your own Animation by using SwiftUI native API.

**Comment by dreampiggy** [comment]
@yonaskolb v1.5.0 version support the convenient transition with duration API. You can upgrade and use that instead.

See: https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/1.5.0

**Comment by yonaskolb** [comment]
Thanks @dreampiggy!
