### ISSUE TITLE
[bug] HEIC image is 90 degree rotated to the right

### ISSUE THREAD

**Issue by Mr-Perfection** [SDWebImage/SDWebImageSwiftUI#119]
I noticed that when I uploaded the HEIC image, it renders with 90 degree rotated image. Is there a way to fix this?

```swift
WebImage(url: url)
        .resizable()
        .placeholder( Image(defaultProfileImage))
        .indicator(.activity)
```

Image looks like this:
<img width="89" alt="Screenshot 2020-06-28 14 20 13" src="https://user-images.githubusercontent.com/10393248/85958501-c1e5c200-b94a-11ea-9d9b-1bd0053d33f4.png">

I want it to look like this:
![IMG_5284](https://user-images.githubusercontent.com/10393248/85958593-6f58d580-b94b-11ea-8da8-c62351e53aca.jpg)

**Comment by Mr-Perfection** [comment]
Nvm, sorry it was my mistake, not a bug.

**Comment by dreampiggy** [comment]
I guess maybe you use the EXIF image. There is already Apple's bug about this, and WebImage/AnimatedImage already fix this.

See more : #102
