### ISSUE TITLE
How do I play .apng or .gif file from bundle in watchOS using SwiftUI

### ISSUE THREAD

**Issue by SagarUnagar** [SDWebImage/SDWebImageSwiftUI#124]
Hi,

Recently I have been required to add an animated image in my stand-alone watchOS app that I'm creating using SwiftUI. So I have added this pod in my project. I also figured out that `AnimatedImage` can be used to load .apng or .gif file from project bundle but that is not available for **watchOS** target.

Can someone please help me to know how can I load .apng or .gif file from my project bundle to my SwiftUI view?

Thanks in advance!

**Comment by dreampiggy** [comment]
WebImage can play animation. See the initializer with isAnimiting binding.

We have example project as well, read and check again.

**Comment by SagarUnagar** [comment]
Thank you @dreampiggy It works now!
