### ISSUE TITLE
GIF with transparent background

### ISSUE THREAD

**Issue by Sinderella** [SDWebImage/SDWebImageSwiftUI#128]
Hello,

I am quite new to Swift, so I am not sure if this is the right place to ask.

I created a window with transparent background and insert a GIF with transparent background. This is what I have.

```swift
// window
        window.isOpaque = false
        window.backgroundColor = NSColor(red: 0, green: 0, blue: 0, alpha: 0)
        window.level = .floating

// view
struct ContentView: View {
    var body: some View {
        AnimatedImage(name: "unnamed.gif")
            .resizable().scaledToFit()
    }
}
```
![image](https://user-images.githubusercontent.com/1926450/88460690-ea9f9f80-ce95-11ea-882c-bf3aeb552e03.png)

I am not sure why the background has some sort of shadow or an afterimage where the arrows are pointing at. Is this something to do with the window property or the library?

I took the image from https://cuttyanimalss.blogspot.com/2020/01/animated-dog-gif-transparent.html.

Thank you!

**Comment by dreampiggy** [comment]
Check your SDWebImage version ? Does you use SDWebImage before 5.8.3 and run on iOS 14 devices ? Which contains bug on UIImageView rendering.


Or, try same URL with WebImage view instead of AnimatedImage.

**Comment by dreampiggy** [comment]
MacOS ? Provide your test enviornment, like macOS version, SDWebImage version.

And please, use same code to run on iOS simulator. UIKit and AppKit behaves different on UIImageView/NSImageView. But I didn't have check and tested on macOS 11 Big Sur.

**Comment by Sinderella** [comment]
Yep, this is on macOS, version 10.15.6 (Catalina).
- SDWebImageSwiftUI version 1.5.0
- SDWebImage 5.8.4

I used it to create a desktop application on macOS, I justed tried with animating WebImage but got the same result.

I just noticed there's some shadow behind the image, disabling it solves the issue.

```swift
window.hasShadow = false
```

Sorry for the trouble!
