### ISSUE TITLE
Could not find module 'SDWebImageSwiftUI' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

### ISSUE THREAD

**Issue by UnrealCherry** [SDWebImage/SDWebImageSwiftUI#132]

**Comment by dreampiggy** [comment]
Any context？I even don't knwo what's your installation way, SwiftPM ? Carthage ? CococaPods ?


And, SDWebImageSwiftUI do not promise any Binary API compatible. If you face any issue related to binary framework, try recompile and check

**Comment by dreampiggy** [comment]
Duplicated for #149
