### ISSUE TITLE
Resize and Cache Images After Download of Full-size Image

### ISSUE THREAD

**Issue by Cyclic** [SDWebImage/SDWebImageSwiftUI#134]
I am attempting to resize images after downloading the full-size image. Is this possible, and can you provide some direction on best practices?

Thanks in advance!

**Comment by dreampiggy** [comment]
Just use the SDWebImage's Image Transformer.

See wiki about this: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#image-transformer-50
