### ISSUE TITLE
App freezes momentarily after dismiss

### ISSUE THREAD

**Issue by Cyclic** [SDWebImage/SDWebImageSwiftUI#136]
After loading a view with image, and then going back to a view with a lot of images, there is a freeze before I can tap or scroll on the view. I ran the time profiler instrument, and this is where it's locking up:
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/553800/95004867-bc30f580-05a5-11eb-839d-020539724464.png">

Any ideas?

Thanks in advance!

EDIT: Commenting out isLoading=true and isLoading=false does improve the performance significantly, but I am sure this has some undesired side effects.

**Comment by dreampiggy** [comment]
That...`isLoading`, is used for `.indicator`...So if you comment that, the indicator will not work at all.

Need some new solution for indicator.

**Comment by dreampiggy** [comment]
Is this new behavior in iOS 14? I haven't have time to test on iOS 14+. Those code works well on iOS 13, and does not cause any recusursive at all.

**Comment by dreampiggy** [comment]
Should be solved by [v2.0.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/2.0.0)
