### ISSUE TITLE
WebImage doesn't always resize to its frame with ForEach inside List

### ISSUE THREAD

**Issue by ykaito21** [SDWebImage/SDWebImageSwiftUI#138]
I use WebImage with ForEach inside List, but it doesn't always work well. First case works with ios 13, but not with ios 14; other cases don't work with ios 13 but work with ios 14.

Is there any possible solution?, or is there any problem with my implementation?

**First Case:**
```
var body: some View {
        return List {
            ForEach(0..<10, id: \.self) { message in
                WebImage(url: URL(string: "https://i.pinimg.com/736x/50/df/34/50df34b9e93f30269853b96b09c37e3b.jpg"))
                    .resizable()
                    .placeholder {
                        Rectangle().foregroundColor(.lightGray)
                    }
                    .indicator(.activity)
                    .aspectRatio(contentMode: .fit)
                    .frame(width: 260)
                    .background(Color.red)
                    .frame(width: 260)
            }
        }
    }
```

**Second Case:**
```
   var body: some View {
        let messageList = some my own list
        return List {
            ForEach(0..<messageList.count, id: \.self) { message in
                WebImage(url: URL(string: "https://i.pinimg.com/736x/50/df/34/50df34b9e93f30269853b96b09c37e3b.jpg"))
                    .resizable()
                    .placeholder {
                        Rectangle().foregroundColor(.lightGray)
                    }
                    .indicator(.activity)
                    .aspectRatio(contentMode: .fit)
                    .frame(width: 260)
                    .background(Color.red)
                    .frame(width: 260)
            }
        }
    }
```

**Third Case:**
```
   var body: some View {
        let messageList = some my own list
        return List {
            ForEach(messageList) { message in
                WebImage(url: URL(string: "https://i.pinimg.com/736x/50/df/34/50df34b9e93f30269853b96b09c37e3b.jpg"))
                    .resizable()
                    .placeholder {
                        Rectangle().foregroundColor(.lightGray)
                    }
                    .indicator(.activity)
                    .aspectRatio(contentMode: .fit)
                    .frame(width: 260)
                    .background(Color.red)
                    .frame(width: 260)
            }
        }
    }
```

**ios 13 Result:**
<div align="center">
<img src="https://user-images.githubusercontent.com/35805590/96573887-b1969000-1309-11eb-9677-1f60d1c96ef6.JPG" width="200" />
<img src="https://user-images.githubusercontent.com/35805590/96573921-beb37f00-1309-11eb-9722-16ef1e68e234.JPG" width="200" />
</div>

**ios 14 Result:**
<div align="center">
<img src="https://user-images.githubusercontent.com/35805590/96573024-89f2f800-1308-11eb-8c7c-bebb61e76f42.png" width="200" />
<img src="https://user-images.githubusercontent.com/35805590/96573115-a8f18a00-1308-11eb-9af0-2382908c3d83.png" width="200" />
</div>

**Comment by atharvsharma1998** [comment]
im also facing this issue. images do not resize to the frame defined inside forEach.

**Comment by dreampiggy** [comment]
Sorry for delay. SwiftUI integration has some inconsistant behavior because of Apple's SwiftUI internal changes. This is a pain for both developer and community.

I'll decide to remove iOS 13 support in next big version, which only considerate the iOS 14's behavior.

**Comment by mboiman** [comment]
I I think I have the same problem, when I fill the picture in a ForEach. The Picture looks good, but the non seen part of the pictures goes over the Frame and blocks the possibility to click buttons from another picture
<img width="339" alt="Bildschirmfoto 2021-01-10 um 09 07 31" src="https://user-images.githubusercontent.com/896819/104117720-d22c2000-5323-11eb-9a3a-0c153e435373.png">

**Comment by nitinkumardb** [comment]
Any solution for this issue?

**Comment by Sagarito** [comment]
Facing the same problem. Also doesn't resize with ForEach inside TabView.

Any solution for this yet?

**Comment by dreampiggy** [comment]
Is this still not works on v2.2.0 ?

**Comment by bitcooker** [comment]
Is this issue solved? https://github.com/SDWebImage/SDWebImageSwiftUI/issues/138#issuecomment-757436415
