### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET Warning

### ISSUE THREAD

**Issue by Rspoon3** [SDWebImage/SDWebImageSwiftUI#140]
This warning appears when using Xcode 12:

IPHONEOS_DEPLOYMENT_TARGET is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99

It doesn't causing any issues, but it would be nice to remove the warning none the less.

**Comment by linkiliz** [comment]
Same. Thank you if you can remove the warning it would be very nice !

**Comment by dreampiggy** [comment]
SDWebImageSwiftUI min deployment target version is iOS 13+.

I guess you means SDWebImage ?

**Comment by linkiliz** [comment]
> SDWebImageSwiftUI min deployment target version is iOS 13+.
> 
> I guess you means SDWebImage ?

Yes, sorry
