### ISSUE TITLE
Installing package seems to have broken my entire projects image handling, persisting after install

### ISSUE THREAD

**Issue by kdthomas2121** [SDWebImage/SDWebImageSwiftUI#141]
![image](https://user-images.githubusercontent.com/32167371/97565078-83860f80-19dd-11eb-98ec-00f3c1ad0e7a.png)
![image](https://user-images.githubusercontent.com/32167371/97565117-91d42b80-19dd-11eb-8e5d-688114e60247.png)

After installing the package, all of my previously working images, stopped working. I've uninstalled the package and the errors are still erroring. Any ideas?

**Comment by dreampiggy** [comment]
SDWebImageSwiftUI does not provide any symbol named `Image`. We have `WebImage` && `AnimatedImage`. Try Xcode clean and have a check.
