### ISSUE TITLE
Website linked in About section is a 404

### ISSUE THREAD

**Issue by aheze** [SDWebImage/SDWebImageSwiftUI#148]
The link in the description doesn't work 😅

<kbd><img width="436" alt="Screen Shot 2020-12-30 at 11 22 35 PM" src="https://user-images.githubusercontent.com/49819455/103399422-f69f2580-4af5-11eb-9e39-9ac03d5ba8ec.png"></kbd>

<img width="1027" alt="Screen Shot 2020-12-30 at 11 22 49 PM" src="https://user-images.githubusercontent.com/49819455/103399424-f868e900-4af5-11eb-8b0b-5581725881b4.png">

**Comment by dreampiggy** [comment]
Emmm..The link seems broken because of GitHub Pages's bug?

It's actually here: https://github.com/SDWebImage/sdwebimage.github.io/blob/master/SDWebImageSwiftUI/index.html

Let me push a new version and have a try as well

**Comment by aheze** [comment]
Yeah that's weird...

**Comment by dreampiggy** [comment]
Fixed. Because of something wrong config of this repo's GitHub Pages.

https://sdwebimage.github.io/SDWebImageSwiftUI/index.html
