### ISSUE TITLE
Could not find module 'SDWebImageSwiftUI' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by color123** [SDWebImage/SDWebImageSwiftUI#149]
Xcode 12.2 running on Mac Mini M1 (Big Sur)
Added SDWebImageSwiftUI v1.5.0 via Swift Package Manager

sample usage:

```
import SwiftUI
import SDWebImageSwiftUI

struct MainView: View {
      ....
      ....
}
```

Error pops up when building (target device: **iPhone 8 (14.3) simulator**)

Tried:
- Clean build
- Restart XCode
- Adding User-Defined VALID_ARCHS with value:  `arm64 arm64e armv7 armv7s i386 x86_64`

**Comment by color123** [comment]
Seems to work when targeting device < 14.3 (e.g. 13.0)

**Comment by dreampiggy** [comment]
Mac Mini M1 can only run `arm64-apple-ios-simulator`.

Because iPhone Simulator on your ARM Mac, can only run arm code, not Intel Mac's x86_64 code.

Can you have a detailed log (use Xcode's Log Navigator's export button) to export the thing for this ? Or try reset all the simulator and restart Mac,  using: `xcrun simctl erase all`

**Comment by color123** [comment]
Here's the exported log from Xcode...

[Build target TestAPp (iOS)_2021-01-05T22-06-18.txt](https://github.com/SDWebImage/SDWebImageSwiftUI/files/5770610/Build.target.TestAPp.iOS._2021-01-05T22-06-18.txt)

**Comment by color123** [comment]
Additional update.. For some reason it works on an iPad Air 4th gen simulator running 14.3

**Comment by color123** [comment]
Also tried resetting the simulator and restarting mac using: `xcrun simctl erase all` but still same error shows up

**Comment by dreampiggy** [comment]
Sounds a strange issue. I can not reproduce on my own Mac environment.

Can you use the Carthage/CocoaPods package manager to test again ? I guess something bug in SwiftPM itself, not our SDK can do.

**Comment by dreampiggy** [comment]
Could not reproduce. If anyone found ways or reason, PR is welcomed.

**Comment by kisspt** [comment]
我遇到了同样的问题，现在有解决办法吗？

**Comment by embassem** [comment]
still have the issue using Macbook pro With M1 pro and Xcode 13.2  installed using SPM
