### ISSUE TITLE
Nested Lazy V & HStacks

### ISSUE THREAD

**Issue by ichbinnicht** [SDWebImage/SDWebImageSwiftUI#150]
My layout hierarchy looks like this:
ScrollView -> LazyVStack -> several LazyHStacks, each with several WebImages.

When scrolling up and down the scrollview, everything works fine for awhile. However, at random times the placeholder is shown and the actual image is not loaded. If I scroll up and down repeatedly, it appears to fix itself and load the image. I have tried to find the source of this issue, but it happens very randomly & unpredictably.

**Comment by dreampiggy** [comment]
iOS 14+ behavior. iOS 13 works well.

Using `@StateObject` will solve this. Release in 2.0.0

**Comment by dreampiggy** [comment]
Should be solved by [v2.0.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/2.0.0)
