### ISSUE TITLE
WebImage does not animate by default

### ISSUE THREAD

**Issue by wilg** [SDWebImage/SDWebImageSwiftUI#151]
The documentation says that `WebImage` supports animated images, but as far as I can tell this only works if I do `WebImage(url: url, isAnimating: .constant(true))`, which is unexpected. Also, sometimes the images stop animating randomly and I cannot figure out why. Perhaps when they move offscreen in a LazyVStack?

**Comment by dreampiggy** [comment]
Legacy behavavior in SDWebImageSwiftUI 1.0

Because I can not change this without an major version bumped.

Will change the WebIamge defaults to animatable in 2.0.0
