### ISSUE TITLE
AnimatedImage not loading gif from assets

### ISSUE THREAD

**Issue by shahbaz07** [SDWebImage/SDWebImageSwiftUI#152]
I am trying to a gif from assets using AnimatedImage, but it's not loading. Please let me know how I can do that. I am using below mention code.

`AnimatedImage(name: "loading.gif", isAnimating: .constant(true))
                            .resizable()
                            .scaledToFit()`

**Comment by dreampiggy** [comment]
> gif from assets

You means, Photos PHAssert library image ?

**Comment by shahbaz07** [comment]
I was adding gif in `Assets.xcassets`. But now I moved it outside in resources folder and it is working fine.

**Comment by dreampiggy** [comment]
xcassets does not supports Animation at all. This is limited by Xcode and Apple, not something we can control. Moving gif or webp out of xcassets and use Bundle path to load is OK.

**Comment by shahbaz07** [comment]
Thanks for the explanation.
