### ISSUE TITLE
Update SDWebImage dependency

### ISSUE THREAD

**Issue by mbuchetics** [SDWebImage/SDWebImageSwiftUI#157]
SDWebImage is already at version 5.10.4, this project is still using 5.7.0. The last release was June 2020.

**Comment by dreampiggy** [comment]
Which dependency lock you from upgrating ?

I notice that both CocoaPods/Carthage/SwiftPM, using the `~>`, which means will upgrade when you need.

**Comment by mbuchetics** [comment]
sorry, my mistake
