### ISSUE TITLE
Freeze of the app

### ISSUE THREAD

**Issue by KALIMI** [SDWebImage/SDWebImageSwiftUI#161]
SDWebImageSwiftUI causes freeze of the app in LazyVStack

this is my code of that part

ScrollView {
  LazyVStack {
      
      CommentTextField().environmentObject(self.profileVM)
      
      ForEach( self.profileVM.comments, id: \.id ) { comment in
          NavigationLink(destination: VisitedProfile(userID: comment.user.id, theme: self.theme)) {
              PostSingleComment(comment: comment, theme: self.theme, toggler: self.$userFullNameColorToggler)
                  .environmentObject(self.profileVM)
          }
      }
  }
}

struct PostSingleComment: View {
    @EnvironmentObject var profileVM: ProfileViewModel
    @State private var isExpanded: Bool = false
    let comment: CommentModel
    let theme: Theme
    @Binding var toggler: Bool
    
    var body: some View {
        
        HStack( alignment: .top ) {
            WebImage(url: URL(string: comment.user.profile_image))
                .resizable()
                .aspectRatio(contentMode: .fill)
                .frame(width: 40, height: 40)
            
            VStack( alignment: .leading) {
                Text( comment.user.fullName )
                    .foregroundColor( toggler ? Color(UIColor(red: 0/255, green: 255/255, blue: 224/255, alpha: 1)) : .white)
                    .font(.custom("Avenir", size: 18))
                    .fontWeight(.heavy)
                
                Text( comment.comment )
                    .foregroundColor(.gray )
                    .font(.custom("Avenir", size: 16))
                    .lineLimit( isExpanded ? nil : 2)
                
                Button(action: {
                    isExpanded.toggle()
                }) {
                    HStack {
                        Spacer()
                        Text(isExpanded ? "Less" : "More")  // add to localizable
                            .font(.custom("Avenir", size: 16))
                            .foregroundColor(.white)
                            .padding(.leading, 8.0)
                            .padding(.top, 0)
                    }
                }
                
                Text( comment.created_at )
                    .foregroundColor(.gray)
                    .font(.custom("Avenir", size: 14))
                    .padding(.top, 8)
            }.padding(.leading)
            
            
        }.padding()
    }

**Comment by dreampiggy** [comment]
Known bug...Move this into #121 

SDWebImageSwiftUI current version can not use with LazyStack in iOS 14. I'll investigate this issue soon.

**Comment by dreampiggy** [comment]
Seems related to the iOS 14's LazyVStack, which will reset the `@State` for any item inside him. Which cause a recursive call to `SDWebImageManager` to load image again...

**Comment by KALIMI** [comment]
as I understood this can be done with changing NavigationLink to isActive: Bool 
this solves this issue but its not correct solution I think

**Comment by KALIMI** [comment]
the problem is connected somehow with SDWebImageSiwftUI and navigation

**Comment by dreampiggy** [comment]
@KALIMI Maybe solved by #162. Reason is in #121

**Comment by dreampiggy** [comment]
Solved by [v2.0.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/2.0.0)
