### ISSUE TITLE
Opening gs links

### ISSUE THREAD

**Issue by SnowballAntrobus** [SDWebImage/SDWebImageSwiftUI#184]
@dreampiggy hello friend I'm confused about this simple code:

        SDImageLoadersManager.shared.loaders = [FirebaseUI.StorageImageLoader.shared]
        SDWebImageManager.defaultImageLoader = SDImageLoadersManager.shared
        let ref = Storage.storage().reference().child(imageName)
        print(ref) //gives the gs link
        let url = NSURL.sd_URL(with: ref)! as URL
        return WebImage(url: url)

When I run this I get a Code=-1002 "unsupported URL" error. Could you please help me?

**Comment by SnowballAntrobus** [comment]
I was trying to follow #70 but I got confused.

**Comment by dreampiggy** [comment]
This should works. Because it's supported via: https://github.com/firebase/FirebaseUI-iOS/pull/841

Maybe you're using the old version of FirebaseUI ?

Provide all your Pod's version, including:

+ SDWebImage
+ SDWebImageSwiftUI
+ FirebaseUI

Or a demo to reproduce this issue ?

**Comment by SnowballAntrobus** [comment]
Thanks so much for responding!!!
These are all my pods:
Installing BoringSSL-GRPC (0.0.7)
Installing Disk (0.6.4)
Installing Firebase (7.10.0)
Installing FirebaseAnalytics (7.10.0)
Installing FirebaseCore (7.10.0)
Installing FirebaseCoreDiagnostics (7.10.0)
Installing FirebaseFirestore (7.10.0)
Installing FirebaseFirestoreSwift (7.10.0-beta)
Installing FirebaseInstallations (7.10.0)
Installing FirebaseStorage (7.10.0)
Installing FirebaseUI (10.0.2)
Installing GTMSessionFetcher (1.5.0)
Installing GoogleAppMeasurement (7.10.0)
Installing GoogleDataTransport (8.4.0)
Installing GoogleUtilities (7.3.1)
Installing PromisesObjC (1.2.12)
Installing Resolver (1.4.1)
Installing SDWebImage (5.11.0)
Installing SDWebImageSwiftUI (2.0.2)
Installing abseil (0.20200225.0)
Installing gRPC-C++ (1.28.2)
Installing gRPC-Core (1.28.2)
Installing leveldb-library (1.22.1)
Installing nanopb (2.30908.0)
I'll work on a demo to reproduce the issue :)

**Comment by SnowballAntrobus** [comment]
I'm seeing on the link that SDWebImage should be 5.6 I'll work to fix this!

**Comment by SnowballAntrobus** [comment]
Thanks! Here they are from my pod file:
- SDWebImage (5.11.0):
    - SDWebImage/Core (= 5.11.0)
- SDWebImageSwiftUI (2.0.2):
    - SDWebImage (~> 5.10)
- FirebaseUI (10.0.2):
    - FirebaseUI/Anonymous (= 10.0.2)
    - FirebaseUI/Auth (= 10.0.2)
    - FirebaseUI/Database (= 10.0.2)
    - FirebaseUI/Email (= 10.0.2)
    - FirebaseUI/Facebook (= 10.0.2)
    - FirebaseUI/Firestore (= 10.0.2)
    - FirebaseUI/Google (= 10.0.2)
    - FirebaseUI/OAuth (= 10.0.2)
    - FirebaseUI/Phone (= 10.0.2)
    - FirebaseUI/Storage (= 10.0.2)
If this doesn't work I'd be more than happy to code up a demo!

**Comment by dreampiggy** [comment]
The dependency version looks correct.

Maybe this because of some bugs. Can you provide some Firebase Storage URL (without authoritation) for me to test ?

A little demo is better.

**Comment by SnowballAntrobus** [comment]
@dreampiggy sounds good I'll set it up in a bit

**Comment by SnowballAntrobus** [comment]
@dreampiggy done! I invited you to the demo the URL in the demo should work. Demo is WebImageGSDemo

**Comment by dreampiggy** [comment]
@SnowballAntrobus Seems works.

You should put that SDK initialize code into `App.swift`, like this

![image](https://user-images.githubusercontent.com/6919743/114516353-e6a7ed80-9c6f-11eb-9252-f51931f35f25.png)


Not the `onAppear` logic, when the `onAppear` called, your image request already been sent and since URLSession does not support `gs://` URL, it will fail.

**Comment by dreampiggy** [comment]
I can add this into the readme or wiki about `How to use some codec / loaders with SwiftUI`.

**Comment by dreampiggy** [comment]
Done. See: [Using with external loaders/caches/coders](https://github.com/SDWebImage/SDWebImageSwiftUI#using-with-external-loaderscachescoders)

**Comment by SnowballAntrobus** [comment]
Thanks so much my friend!!!
