### ISSUE TITLE
images disapears in list editMode manually set

### ISSUE THREAD

**Issue by theromis** [SDWebImage/SDWebImageSwiftUI#19]
Trying to use edit mode and images "hiding".
Original `Image` works fine.

Could you help me to debug?
```swift
struct SubscriptionDetails: View {
    var image: String
    var title: String
    var text: String
    var date: String
    var messages: Int
    
    var body: some View {
                    //Image("Illustration1")
                    WebImage(url: URL(string: image))
                        //.renderingMode(.original)
                        .resizable()
                        .aspectRatio(contentMode: .fit)
                        .frame(width: 80, height: 80)
                        .cornerRadius(20)
    }
}
```

```swift
    var body: some View {
        NavigationView {
            List {
            ForEach(updateData) { item in
                NavigationLink(
                destination: UpdateDetail(title: item.title, text: item.text, image: item.image), tag: item.id, selection: self.$selection) {
                    SubscriptionDetails(image: item.image, title: item.title, text: item.text, date: item.date, messages: item.messages)
                        .onTapGesture {
                            self.selection = item.id
                    }
                }
            }
            .onDelete { index in
                print("delete", index)
            }
            }
            .environment(\.editMode, .constant(self.isEditing ? EditMode.active : EditMode.inactive))
        }
    }
```

**Comment by theromis** [comment]
<img width="399" alt="Screen Shot 2019-10-10 at 1 01 27 AM" src="https://user-images.githubusercontent.com/3720229/66550754-e965d780-eafa-11e9-92c0-0aabf4970b0b.png">
<img width="404" alt="Screen Shot 2019-10-10 at 1 01 39 AM" src="https://user-images.githubusercontent.com/3720229/66550755-e965d780-eafa-11e9-8f03-5b15d18e47d0.png">
<img width="406" alt="Screen Shot 2019-10-10 at 1 04 01 AM" src="https://user-images.githubusercontent.com/3720229/66550756-e965d780-eafa-11e9-8681-31ae1ef5935e.png">

**Comment by dreampiggy** [comment]
For `WebImage`, it will render a empty Image, when new `View.body` method called and then with a `onAppear`. Maybe it's a bug that sometimes the `onAppear` not called so it will become empty ?

Set a breakpoint here may help: https://github.com/SDWebImage/SDWebImageSwiftUI/blob/master/SDWebImageSwiftUI/Classes/WebImage.swift#L53

**Comment by dreampiggy** [comment]
Can you please provide a runnable demo ? For example, provide a mock code of your `UpdateDetail` (a placeholder view is OK), and your mock data of `updateData`, for me to debug with.

**Comment by dreampiggy** [comment]
One line code fix this, seems another cases that cause `onAppear` not been called. So instead, we prefer to always load image if empty.


[屏幕录制2019-10-10下午5.50.27.zip](https://github.com/SDWebImage/SDWebImageSwiftUI/files/3711680/2019-10-10.5.50.27.zip)

**Comment by dreampiggy** [comment]
Should be solved. You can try to upgrade to [v0.3.2](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/0.3.2) version.

**Comment by dreampiggy** [comment]
@theromis Is this been solved ?

**Comment by theromis** [comment]
@dreampiggy thank you for so quick reaction, yes 0.3.2 solved an issue

**Comment by dreampiggy** [comment]
@theromis If you find this library helpful for you, please give us a Star and help us for some propaganda, thanks !

**Comment by theromis** [comment]
@dreampiggy done :)
