### ISSUE TITLE
ITMS-90338: Non-public API usage&nbsp;

### ISSUE THREAD

**Issue by liseami** [SDWebImage/SDWebImageSwiftUI#191]
Xcode 13 beta

ITMS-90338: Non-public API usage&nbsp;- The app references non-public symbols in Frameworks/SDWebImage.framework/SDWebImage: ___NSArray0__struct, ___kCFBooleanTrue. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at

**Comment by azeezat** [comment]
Navigate to ios/yourAppName.xcodeproj/xcshareddata/xcschemes/yourAppName.xcscheme and replace every instance of "**Debug**" with "**Release**"

**Comment by dreampiggy** [comment]
WTF is this ?
