### ISSUE TITLE
Insert Local Image?

### ISSUE THREAD

**Issue by afern247** [SDWebImage/SDWebImageSwiftUI#203]
Hi, how can I insert a local Image? I tried the web one but doesn't work:

`WebImage(url: URL(string: "exchange-alt-solid"))`

It's a SVG Format

**Comment by msa1422** [comment]
Hi @afern247,
Did you find any workaround for this?
Please share the technique that you're using to load locally stored sag images.

**Comment by msa1422** [comment]
I found the workaround.
You have to provide url like such
```
WebImage(url: URL(fileURLWithPath: yourBundle.path(forResource: "your_image", ofType: "svg") ?? ""))
    ...
```

**Comment by dreampiggy** [comment]
Just use URL with filePath, it works as designed.
