### ISSUE TITLE
Failed to download image with error Download marked as failed because response status code is not in 200-400

### ISSUE THREAD

**Issue by RajaZahid** [SDWebImage/SDWebImageSwiftUI#209]
Try to display image but getting error:
Failed to download image with error Download marked as failed because response status code is not in 200-400

Try following image URL:
http://admin-qa.fetchmyorder.com/uploads/Sample3.jpg

Image URL is valid and able to see image in browser.

**Comment by RajaZahid** [comment]
Try to display image but getting error:
Failed to download image with error Download marked as failed because response status code is not in 200-400

Try following image URL:
https://fetchmyorder.com/wp-content/uploads/2020/08/Ortons.jpg

Image URL is valid and able to see image in browser.

**Comment by RajaZahid** [comment]
Although it is loading fine with 2nd attempt.

**Comment by vebbis321** [comment]
I have the exact same problem. When I open the SettingsView in my project, the URL is there and it is valid, but the image doesn't show up.

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-01-20 at 11 56 30](https://user-images.githubusercontent.com/57636432/150325833-2d25278b-5a1f-453e-8218-323efe31a8d0.png)

But then I select one of the settings and go back (no new callbacks or new network calls done), and now the image is showing. 

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-01-20 at 11 56 45](https://user-images.githubusercontent.com/57636432/150326120-b836c762-4cf4-4318-82f9-7f81b8455d4a.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-01-20 at 11 57 55](https://user-images.githubusercontent.com/57636432/150326125-a58bff5d-0f61-4ca5-95ec-6652257fe713.png)

I also ran the exact same code with AsyncImage without any errors.

**Comment by dreampiggy** [comment]
Use API : https://sdwebimage.github.io/SDWebImage/Classes/SDWebImageDownloaderConfig.html#/c:objc(cs)SDWebImageDownloaderConfig(py)acceptableStatusCodes

to change the "valid HTTP status code", which is defaults to `[200, 400)`

**Comment by UI10** [comment]
`acceptableStatusCodes` is not available in` SDWebImageDownloaderConfig.h` file on SDWebImage 5.10.4
