### ISSUE TITLE
Xcode 14 - SwiftUI warning

### ISSUE THREAD

**Issue by guidev** [SDWebImage/SDWebImageSwiftUI#222]
If you try to run the sample app on Xcode 14 beta 5 you get the following warnings.
<img width="1605" alt="Screenshot 2022-08-09 at 18 38 52" src="https://user-images.githubusercontent.com/1105813/183708599-c29c5ee1-52d1-45aa-ae45-1d28b9f9c724.png">

**Comment by guidev** [comment]
<img width="1372" alt="Screenshot 2022-08-09 at 18 45 56" src="https://user-images.githubusercontent.com/1105813/183709849-f356af41-6409-473b-a569-ada9d0a92562.png">

**Comment by Teglgaard** [comment]
+1
At the same time our logs are spammed with
[SwiftUI] Publishing changes from within view updates is not allowed, this will cause undefined behavior.

**Comment by lukeredpath** [comment]
Also seeing this - this is a genuine bug within the library because it is triggering a method from within the view body that has side effects, one of which is mutating some published state:

Specifically, `WebImage` does this:

```swift
    public var body: some View {
        // This solve the case when WebImage created with new URL, but `onAppear` not been called, for example, some transaction indeterminate state, SwiftUI :)
        if imageManager.isFirstLoad {
            imageManager.load()
        }
        ...snip...
    }
```

I have no context as to _why_ this change was added but it is fundamentally wrong. Side effects should not be performed from within a SwiftUI's view body - this body method can potentially called many times (every time the view's state changes). In this case, calling `.load()` not only triggers a side effect, but it causes the @Published `isLoading` to be mutated in the middle of the view update cycle.

**Comment by BugMonkey** [comment]
+1

**Comment by RMehdid** [comment]
also having the same issue, with the bug affecting my navigationStack and moves me back to previous page, needs a fix asap, at least a workaround for now...

**Comment by BugMonkey** [comment]
I noticed that the picture flickered a bit in iOS16 beta 5
🥲

**Comment by tichise** [comment]
I encountered a similar message in my environment.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/43707/187577660-bc9461f7-431c-4bbd-99d5-37ed8a9d9360.png">

**Comment by yoshirozay** [comment]
+1

**Comment by frlefebvre** [comment]
Any chance this gets fixed before iOS 16's release?

**Comment by dreampiggy** [comment]
Hi.

This current repo's code, need a refactory to make it works with latest SwiftUI. And drop the usage of that `ObservedObject` using `StateObject`.

If someone has expert coding experience, PR is welcomed.

Currently I'm working on LLVM/Swift toolchain in this year, so may not have enough time to maintain this changes. But I'll try to back to this repo once I have some extra time.

**Comment by Sri2611** [comment]
+1

**Comment by garrettrayj** [comment]
Following @lukeredpath's hint, I made some changes that seem to fix things on iOS 16.

https://github.com/SDWebImage/SDWebImageSwiftUI/compare/master...garrettrayj:ios16-undefined-behavior

I haven't tested AppKit and I bet backwards compatibility is messed up, but the changes appear mainly to be removing old workarounds that are no longer needed. Story of my life with SwiftUI, so I'm feeling confident enough to roll with 'em for the sake of getting iOS 16 updates out the door.

**Comment by lukeredpath** [comment]
If you don't need backwards compatibility another option would be to see if the built in AsyncImage does what you need and have one less third party dependency in your codebase. That's my plan.

**Comment by Teglgaard** [comment]
@garrettrayj - Great work - Will you make a PR? Then it can be reviewed.

**Comment by tichise** [comment]
I had the same error with iOS16 RC version.

**Comment by Jeyhey** [comment]
This warning appears with the latest SwiftUI update but the issue impacts all SwiftUI versions. For instance, I have observed that screens that have a SDWebImage as first element are not correctly rendered in a navigation animation (i.e. when they swipe in from right to left).

**Comment by dreampiggy** [comment]
Please have a try with [v2.1.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/2.1.0)

**Comment by Jeyhey** [comment]
Seems to work perfectly now. Thank you!!
