### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by iowais-dev** [SDWebImage/SDWebImageSwiftUI#226]
getting purple warning in Xcode 14
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

**Comment by arbyruns** [comment]
Seeing this as well.

**Comment by umair-khan97** [comment]
After Xcode and iOS 16 update

**Comment by yuri-qualtie** [comment]
Same issue for Xcode 14 and iOS 16

**Comment by ruslan-qualtie** [comment]
+1

**Comment by aregler** [comment]
You can take a look at #222 and #225.

**Comment by oglerma** [comment]
Thank you for looking into this. I am seeing this affect our app when iOS 16 was released.

**Comment by dreampiggy** [comment]
Please have a try with [v2.1.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/2.1.0)

**Comment by iowais-dev** [comment]
Thanks :)
