### ISSUE TITLE
`@SwiftUI.StateObject` crash on iOS 13

### ISSUE THREAD

**Issue by hstdt** [SDWebImage/SDWebImageSwiftUI#230]
`StateObject` crash with `dyld: lazy symbol binding failed: Symbol not found:`

<img width="1326" alt="CleanShot 2022-09-20 at 19 33 37" src="https://user-images.githubusercontent.com/10215098/191249977-d4117c7e-a2cf-4af9-a8e6-3fb81c7ca375.png">

PS: the `Backport` structure is conflict with https://github.com/shaps80/SwiftUIBackports for same name if both are imported

**Comment by dreampiggy** [comment]
[v2.2.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/2.2.0) released
