### ISSUE TITLE
V2.2.0 iOS 16.0 cpu up to 100%

### ISSUE THREAD

**Issue by wapony** [SDWebImage/SDWebImageSwiftUI#234]
I update to v2.2.0, iPhone 11pro iOS 16.0, the cpu up to 101%, when I delete the WebImage code, the cpu down to 0%

**Comment by wapony** [comment]
> Reproduce demo ? Provide the code snippet of your view structure

 WebImage(url: getHeaderImageURL())
                            .resizable()
                            .placeholder(Image("ic_placeholder_tws_headset_big"))
                            .indicator(.activity)
                            .transition(.fade(duration: 0.5))
                            .scaledToFit()
                            .frame(width: headImageWidth, height: headImageWidth, alignment: .center)
                            .frame(width: 236, height: 236)
                            .opacity(earbudDetail.isConnected == .connected ? 1 : 0.2)

After the test,  if `getHeaderImageURL()` return nil, the cpu will up to 101%

**Comment by wapony** [comment]
> Reproduce demo ? Provide the code snippet of your view structure
```Swift
WebImage(url: getHeaderImageURL())
    .resizable()
    .placeholder(Image("ic_placeholder_tws_headset_big"))
    .indicator(.activity)
    .transition(.fade(duration: 0.5))
    .scaledToFit()
    .frame(width: headImageWidth, height: headImageWidth, alignment: .center)
    .frame(width: cardWidth, height: cardWidth)
    .opacity(earbudDetail.isConnected == .connected ? 1 : 0.2)
```

if `getHeaderImageURL()` return nil, the cpu will up to 101%

**Comment by dreampiggy** [comment]
Seems talk about the nil `URL` case.
