### ISSUE TITLE
transition NOT Working!

### ISSUE THREAD

**Issue by wishWinds** [SDWebImage/SDWebImageSwiftUI#247]
The `.transition` modifier is not working.
I try to trace the code where placeholder change to real image when load url finished. but I can't find.
Is anyone figure out why `.transition` is not working?

**Comment by wishWinds** [comment]
fixed.  plan to open a pull request

**Comment by dreampiggy** [comment]
@wishWinds PR is welcomed. Is your fixes works ?

**Comment by wishWinds** [comment]
@dreampiggy Hi. PR is created. That fix my problems.

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/SDWebImageSwiftUI/pull/250

Can you have a test again with the dropping iOS 13 branch ?
