### ISSUE TITLE
App Crashed 

### ISSUE THREAD

**Issue by ghost** [SDWebImage/SDWebImageSwiftUI#254]
<img width="536" alt="Screenshot 2023-01-25 at 10 21 23 PM" src="https://user-images.githubusercontent.com/119960360/214627109-7e8a4fcb-3c38-422c-b421-158c83a2122f.png">

Somehow app gets crashed loading SVG images from url while i am changing tab in my app

Blow warning i got at the end with crash 

Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions

**Comment by jazzplanok1** [comment]
![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/67549708/a49e9e7f-7e7b-4cec-91cb-d3ef1bb6de2d)

**Comment by jazzplanok1** [comment]
![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/67549708/79a8120f-b077-4c16-a51b-0c2b3d378693)

**Comment by jazzplanok1** [comment]
![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/67549708/dadcbdf3-4347-4690-8e82-2af0bdac9645)

**Comment by dreampiggy** [comment]
If you use SDWebImageSVGCoder, maybe you can check https://github.com/SDWebImage/SDWebImageSVGCoder/pull/44

Or, a better solution, try to use SDWebImageSVGNativeCoder instead


A personal tip:

DO NOT USE SVG on Apple Platform, use PDF instead
