### ISSUE TITLE
Compiler error with swift 5.8

### ISSUE THREAD

**Issue by jackywpy** [SDWebImage/SDWebImageSwiftUI#259]
I have a compiler error when using xCode 14.3, swift 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)):

failed to verify module interface of 'SDWebImageSwiftUI' due to the errors above; the textual interface may be broken by project issues or a compiler bug.

<img width="1050" alt="截屏2023-04-06 11 07 20" src="https://user-images.githubusercontent.com/1032923/230262578-677a6569-3094-4bae-852a-1a1971822461.png">

thanks

**Comment by dreampiggy** [comment]
What build system did you use ?

+ CocoaPods
+ SwiftPM 
+ Carthage (prebuilt-binary framework)

**Comment by Willicious-k** [comment]
@dreampiggy 

encountered same issue here.

I used `CocoaPods` + `Static` setting like this.

build using Xcode 14.3 

Podfile
```
platform :ios, '14.0'

target 'some-target-name' do
  # use_frameworks!

  pod 'SDWebImage', '5.12.1', :modular_headers => true
  pod 'SDWebImageSwiftUI', '2.2.2'

end
```

**Comment by higekick** [comment]
same here !

**Comment by dreampiggy** [comment]
Will fix in later. These months have no time in iOS development, focus on LLVM/Swift toolchain.

**Comment by Niccari** [comment]
(Workaround, CocoaPods + Xcode 14.3)

Setting `Project: Pods > Target: SDWebImageSwift > Settings > Build Libraries for Distribution` to "No" and I was able to build the app.

**Comment by dreampiggy** [comment]
Is this the same issue as #261 ? See comments there

**Comment by dreampiggy** [comment]
> 

@niccari Oh. You're using CocoaPods with Library Evolution on. The SPM does not enable Library Evolution, maybe this cause problem.

**Comment by dreampiggy** [comment]
@Willicious-k @higekick @Niccari  Got the reason. It because of your `SDWebImage` version.

If you upgrade to `5.15.0`+, it does not contains any issue at all

**Comment by dreampiggy** [comment]
Can you use the `Static Framework` integration to test ?

```
use_frameworks! :linkage => :static
```

![image](https://user-images.githubusercontent.com/6919743/233835803-ac3cbaa0-0f32-4139-8b78-a72130f3ba71.png)

**Comment by Niccari** [comment]
> Seems because of that Static Lib + Library Evolution YES cause the issue

Agreed, I'm using Static Framework(not setting `use_frameworks!`) and Library Evolution YES in the project.

in `Pods/Pods.xcodeproj/project.pbxproj`, there was no "BUILD_LIBRARY_FOR_DISTRIBUTION" key and somehow "YES" used as defaults so I'll investigate why it happens.

Checked below situations.

- ❌ Build Failed: (Current settings) Static Libs + BUILD_LIBRARY_FOR_DISTRIBUTION = Yes
- ✅ Build Succeeded: Dynamic Libs for SDWebImage and SDWebImageSwiftUI + BUILD_LIBRARY_FOR_DISTRIBUTION = Yes
- ✅ Build Succeeded: Static Libs + BUILD_LIBRARY_FOR_DISTRIBUTION = No
- ✅ Build Succeeded: Dynamic Libs for SDWebImage and SDWebImageSwiftUI + BUILD_LIBRARY_FOR_DISTRIBUTION = No

**Comment by Niccari** [comment]
> And, what cause CocoaPods use Library Evolution on ? I try that :modular_headers => true it does not enable this by default.

In SDWebImageSwiftUI.podspec, it seems that swift interface needs to be generated and BUILD_LIBRARY_FOR_DISTRIBUTION is set to "yes".
https://github.com/SDWebImage/SDWebImageSwiftUI/commit/056cc697131cc71946cd0b4bf25628e4cc43d25a

**Comment by Niccari** [comment]
@dreampiggy 

> And, what cause CocoaPods use Library Evolution on ? I try that :modular_headers => true it does not enable this by default.

In SDWebImageSwiftUI.podspec, it seems that swift interface needs to be generated and BUILD_LIBRARY_FOR_DISTRIBUTION is set to "yes".
https://github.com/SDWebImage/SDWebImageSwiftUI/commit/056cc697131cc71946cd0b4bf25628e4cc43d25a

**Comment by dreampiggy** [comment]
Thanks! @Niccari 

Seems that `Podspec` hack for `BUILD_LIBRARY_FOR_DISTRIBUTION` should be removed. I doubt what issue cause me to add this at that time (Xcode 12, 2 years agao....)

But seems this is the correcy way to go, since whether or not to enable `Library Evolution` is controlled by user who integrate, not the lib author
