### ISSUE TITLE
Xcode 14.3

### ISSUE THREAD

**Issue by Patresko** [SDWebImage/SDWebImageSwiftUI#261]
It's not possible to compile code on latest version of Xcode 14.3. Added via Xcode Package Dependencies.

Error:
`missing required module "SDWebImage"`

**Comment by jpmcglone** [comment]
I'm having this issue. I have a sub package that has the dependencies added correctly, but im getting this error in Previews only (I can compile, i can build to device, but previews don't work at all and give this same error)

**Comment by jpmcglone** [comment]
I'm having this issue. I have a sub package that has the dependencies added correctly, but im getting this error in Previews only (I can compile, i can build to device, but previews don't work at all and give this same error)

**Comment by dreampiggy** [comment]
Need a demo project to show this issue. Open `SDWebImageSwiftUI/Package.swift` can build without error. Is this exists only on a App project (which use Xcode's Package dependency?)

**Comment by dreampiggy** [comment]
Seems using demo run does not contains any issue:

![image](https://user-images.githubusercontent.com/6919743/233834956-3ce80070-f561-46f7-8341-5a459c68deb8.png)

**Comment by dreampiggy** [comment]
Seems using Preview does not contains this issue ? Click run to play 
![image](https://user-images.githubusercontent.com/6919743/233835077-05edc7de-f7bd-4125-a2a0-bb793b3b129b.png)

**Comment by dreampiggy** [comment]
[SDWebImageSwiftUIDemo.zip](https://github.com/SDWebImage/SDWebImageSwiftUI/files/11303447/SDWebImageSwiftUIDemo.zip)

**Comment by dreampiggy** [comment]
From the #259 Maybe you should disable Library Evolution when you integrate with `Static Library`

**Comment by dreampiggy** [comment]
Solved in v2.2.3
