### ISSUE TITLE
visionOS support

### ISSUE THREAD

**Issue by kevinwang-oversoul** [SDWebImage/SDWebImageSwiftUI#273]
Hi,

Is there any plan to support visionOS platform?
Many concepts don't transfer to visionOS such as UIScreen, so it's impossible to build on visionOS at the moment.

I see there are 2 PRs relating to this issue, but they are paused for some reason. Could you confirm the status please @dreampiggy ?

https://github.com/SDWebImage/SDWebImage/pull/3556
https://github.com/SDWebImage/SDWebImageSwiftUI/pull/267

**Comment by dreampiggy** [comment]
The full support need `Package Manager` , which means, CocoaPods and SwiftPM

Both these tools need release their version. Or you can just do something like me, to use prebuilt binary of SDWebImage and integrate to your visionOS App.

**Comment by dreampiggy** [comment]
Release v3.0.0-beta, support build for visionOS (without CocoaPods)

https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/3.0.0-beta

You can only use Xcode's dependency package, or build using the manual steps from readme, to integrate and test on your visionOS App.

**Comment by thatvirtualboy** [comment]
To use SDWebImageSwiftUI with VisionOS, do we just change the Dependency to use `Exact Version` of `3.0.0`? Thanks!

**Comment by dreampiggy** [comment]
Use beta version just OK
