### ISSUE TITLE
The behavior of aspectRatio between AnimatedImage and WebImage is not same

### ISSUE THREAD

**Issue by hstdt** [SDWebImage/SDWebImageSwiftUI#279]
As screenshot shows, AnimatedImage with aspectRatio is larger/smaller than expected.

![CleanShot 2023-11-03 at 10 59 29](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/10215098/0a7a659b-4b9a-4bed-afdb-ab8c1d039751)

Environment: 
Xcode 15.1 beta, iOS 17
Demo Project:  [SDDisplayDemo.zip](https://github.com/SDWebImage/SDWebImageSwiftUI/files/13246388/SDDisplayDemo.zip)

**Comment by hstdt** [comment]
Update: with `scaledToFit()` or `scaledToFill()`

![CleanShot 2023-11-03 at 11 11 08](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/10215098/b476d6fe-b831-4830-b322-b717ba0e03a0)

**Comment by dreampiggy** [comment]
For animated image, to workaround a old iOS 13 issue, the actualy image view is the subview of an container. And use auto layout to edge to edge of that container

This history work on iOS 13-16, seems broken. Don't know whether compatible issue with auto layout with SwiftUI 's layout system or other case

Need time to investigate

**Comment by dreampiggy** [comment]
Can you use the 3.0.0-beta2 to test the same behavior ?

**Comment by hstdt** [comment]
@dreampiggy  Xcode 15.2 beta with v3.0.0-beta.2/v3.0.0-beta.3 

![CleanShot 2023-12-20 at 10 18 54](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/10215098/d9982bbb-8e5b-4076-9c1f-aa33e74181c9)

**Comment by dreampiggy** [comment]
Seems the bug still exists....

Do you knwo the layout constraint about auto layout X SwiftUI ? Need more time or other people to help with this.

**Comment by hstdt** [comment]
What's the point of `_AspectRatioLayout(aspectRatio: aspectRatio, contentMode: contentMode)`, I removed this and everything is ok now(only tested on iOS 17).

demo project: 
[SDDisplayDemo.zip](https://github.com/SDWebImage/SDWebImageSwiftUI/files/13724056/SDDisplayDemo.zip)

![CleanShot 2023-12-20 at 14 50 47](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/10215098/c8006e8e-4b07-4fe0-a3db-772d717c0493)

![CleanShot 2023-12-20 at 14 55 06](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/10215098/dfcd16b0-4808-4577-9340-225df76fbf47)

**Comment by dreampiggy** [comment]
It's used to implements the custom aspectRatio. Like `0.5`

Not content mode. SwiftUI this modifier provide 2 function (transform) and (display scale mode) using the 1 API, which is hard for UIKit based to implements

**Comment by dreampiggy** [comment]
Try using

```
Image()
.resizable
.aspectRatio(0.5, .aspectFit)
```

To see the result.

**Comment by dreampiggy** [comment]
I think the behavior works on iOS 16-, but break on iOS 17+

You can test the lower version as well, from the iOS 14 ~ iOS 17, each iOS version need to test the behavior again.

**Comment by arnauddorgans** [comment]
Any update here?
