### ISSUE TITLE
Is there any way to clear a running gif from your RAM when you are no longer looking at it?

### ISSUE THREAD

**Issue by Animatnetic** [SDWebImage/SDWebImageSwiftUI#280]
As more gifs are added, this RAM measurement increases and increases. I have not had the patience to sit down and see what happens if it reaches a high enough number to crash or cause a slow down but does trigger some concern. Can someone please clarify this for me?

<img width="904" alt="Screenshot 2023-11-11 at 19 08 28" src="https://github.com/SDWebImage/SDWebImageSwiftUI/assets/83513114/e1bc9795-71ca-4891-a997-915f90943546">

_I am asking for SwiftUI use_

**Comment by dreampiggy** [comment]
The same. Just call SDImageCache.removeMemoryCache when needed.

Actually if you use the AnimatedImage, it will use a buffer count to determine the RAM pressure and free the frame if needed

**Comment by Animatnetic** [comment]
Thank you very much, I shall close the issue in positive light due to your clarification.
