### ISSUE TITLE
Change SVG color with foregroundStyle

### ISSUE THREAD

**Issue by kekko7072** [SDWebImage/SDWebImageSwiftUI#283]
I have this code loading svg and i want to change the color of svg:

```
WebImage(url: URL(string: element.icon.url), options: [], context: [.imageThumbnailPixelSize : CGSize.zero])
                                                .placeholder {ProgressView()}.resizable().frame(width: 22, height: 22).foregroundStyle(.blue)
```
I read all the docs and i'm not finding a way to do it.

**Comment by kekko7072** [comment]
for the moment i'm using .opacity(0.5) because i need it grey, but will be a nice feature.

**Comment by dreampiggy** [comment]
Seems this syntax looks great and easy, but currently the implementation does not use the actual `vector` or `template` image internally.

The SVG on SwiftUI will use the `bitmap` snapshot for your WebImage requests. So it can no change the background color or size (which will cause blur) dynamically. Maybe I can update the readme.

But this may be something in the future we can implements, kept for here

**Comment by dreampiggy** [comment]
This apply the same for `PDF` vector image. The `WebImage` can not actually host vector image, it will convert it into bitmap snapshot, so it's fixed size and no-longer been template to change color or size without lossing details

**Comment by dreampiggy** [comment]
Tested the rendering mode seems work on `WebImage`, you can check this as well

![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/6919743/990ed146-71c8-423f-9808-ac51d27a0b11)

**Comment by kekko7072** [comment]
Yes worked perfectly.

**Comment by dreampiggy** [comment]
Added this tip into README: https://github.com/SDWebImage/SDWebImageSwiftUI/commit/6ca98e077b873f59c7cf1fad13f1f1d0f6449c74
