### ISSUE TITLE
Unit test crash on macOS 12 with `Attempted to read an unowned reference but object 0x12345 was already deallocated`

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImageSwiftUI#286]
This is happended in #285 

The crash does not exists on macOS 13 or 14...Only 12.
The crash does not exists on watchOS / iOS / tvOS , only macOS 12...

Hope @Kyle-Ye can help for this.

### Reproduce
1. branch: feature/export_animated_image_view_type
2. `pod install`
3. Open SDWebImageSwiftUI.xcworkspace
4. Run `testAnimatedImageWithData`

**Comment by Kyle-Ye** [comment]
Have a macOS 12 device on hand. You can add me as "Assignees" and I'll give it a try tonight.

**Comment by Kyle-Ye** [comment]
Looks like the CI is using macOS 12.7.1 + Xcode 14.1. I'll install it and try it again later

**Comment by Kyle-Ye** [comment]
Run it through CLI via `/Applications/Xcode-14.1.0.app/Contents/Developer/usr/bin/xcodebuild clean -workspace SDWebImageSwiftUI.xcworkspace -scheme "SDWebImageSwiftUITests macOS" -destination platform=macOS,arch=arm64 -configuration Debug CODE_SIGNING_ALLOWED=NO` produced it.

Here is my local crash report.

[SDWebImageSwiftUIDemo-macOS-2023-11-30-230327.ips.zip](https://github.com/SDWebImage/SDWebImageSwiftUI/files/13514670/SDWebImageSwiftUIDemo-macOS-2023-11-30-230327.ips.zip)

However after this crash build, I can't reproduce it again even with a clean build.
