### ISSUE TITLE
如何支持iWatch使用animatedImage

### ISSUE THREAD

**Issue by yuantan** [SDWebImage/SDWebImageSwiftUI#289]
API标记支持，但是又被#if 宏过滤掉了？？？

**Comment by yuantan** [comment]
如何支持WatchOS 自定义 动画

**Comment by dreampiggy** [comment]
Use `WebImage` for animation and GIF

**Comment by dreampiggy** [comment]
The README already point it out that `WebImage` support GIF

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/SDWebImageSwiftUI?tab=readme-ov-file#demo
