### ISSUE TITLE
Readme.md link docs is wrong

### ISSUE THREAD

**Issue by alrocha** [SDWebImage/SDWebImageSwiftUI#290]
Hey!!

I was trying to find the advanced docs and seems like the URL that is pointing to is broken: 

<img width="517" alt="image" src="https://github.com/SDWebImage/SDWebImageSwiftUI/assets/8307263/fac3dee8-1f25-46c8-b3ea-1c719f478042">

It should be https://sdwebimage.github.io/documentation/sdwebimageswiftui/ instead of https://sdwebimage.github.io/SDWebImageSwiftUI/

**Comment by dreampiggy** [comment]
Fixed.
