### ISSUE TITLE
Support VisionOS?

### ISSUE THREAD

**Issue by ismyhc** [SDWebImage/SDWebImageSwiftUI#297]
Any plans to support VisionOS? Looking at the Package.swift I don't see the platform support for it.

Would love to use it in an app Im building. SDWebImage is superior to AsyncImage in every way :)

**Comment by dreampiggy** [comment]
Supported to compile for visionOS

No package manager (SPM or CocoaPods) support because this requires XCode 15 and Swift 5.9

Which breaks exists XCode 14 users.

You can clone or build a binary XCFramework and use in visionOS

**Comment by dreampiggy** [comment]
See #273 

But anyway, we can release in the new major version which break XCode 14 support

**Comment by ismyhc** [comment]
> Supported to compile for visionOS
> 
> 
> 
> No package manager (SPM or CocoaPods) support because this requires XCode 15 and Swift 5.9
> 
> 
> 
> Which breaks exists XCode 14 users.
> 
> 
> 
> You can clone or build a binary XCFramework and use in visionOS

Okay understandable. Thanks! 🙏

**Comment by dreampiggy** [comment]
Seems Package.swift don't need update Xcode still can resolve the platform.

For CocoaPods, it's already updated. In 2.2.7 version and 3.0 version
