### ISSUE TITLE
gif animation stops when I quickly switch URLs only on Target of watchOS

### ISSUE THREAD

**Issue by alfredcc** [SDWebImage/SDWebImageSwiftUI#312]
Hello, maintainer,
I have two strange bugs to report. I saw that the issue with loading a `nil` URL had been fixed before [Fix nil url reloading](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/3.0.1), but it still exists on watchOS. Additionally, there's another issue on watchOS where the gif animation stops when I quickly switch URLs, which doesn't happen on the phone. I wrote a demo to easily reproduce this problem and created a file named `FastSwitchGifView`.

https://github.com/alfredcc/SDWebImageSwiftUI/tree/bug-report-on-watchOS

**Comment by alfredcc** [comment]
workaround is to add some delay when witch to another gif file
```swift
 DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
    // update gif url here
}
```

**Comment by alfredcc** [comment]
Fix on https://github.com/SDWebImage/SDWebImageSwiftUI/pull/313

**Comment by alfredcc** [comment]
I find that the method `onAppear` is not called on wathOS
https://github.com/SDWebImage/SDWebImageSwiftUI/blob/master/SDWebImageSwiftUI/Classes/WebImage.swift?#L308

**Comment by dreampiggy** [comment]
If you read the code you will find only watchOS use different implementation. Because UIKit is not available

**Comment by alfredcc** [comment]
Yes, I saw that `onPlatformAppear` used UIKit/AppKit behavior. On watchOS, this fallback method was not used. The buggy behavior of `onAppear` in SwiftUI disrupted some logic in the application. Therefore, currently, there isn't a very good way to handle this issue on watchOS.

**Comment by dreampiggy** [comment]
May find a way to remove the dependency of `onPlatformAppear` and implments the similiar effect.

But I doubt this will break that `.indicator/.placeholder` behavior, which behaves like a composition view, not a single stateful view (no sounds suitable for SwiftUI)
