### ISSUE TITLE
How can we specify URL image scale in WebImage

### ISSUE THREAD

**Issue by Kyle-Ye** [SDWebImage/SDWebImageSwiftUI#322]
The corresponding SwiftUI.AsyncImage snippets.

```swift
let scale = UIScreen.main.scale
let imageName = "\(baseURL)/\(name)_\(Int(scale))x.png"

return AsyncImage(
    url: URL(string: imageName),
    scale: scale
) { image in
    ...
} placeholder: {
    ...
}
```

**Comment by dreampiggy** [comment]
Using `.context([.imageScale] = 2)` ?

See `SDWebImageContext.h`

**Comment by dreampiggy** [comment]
Maybe we can polish this API to automatically pass down the scale into the `context` arg used in SDWebImage Core

**Comment by Kyle-Ye** [comment]
> Maybe we can polish this API to automatically pass down the scale into the `context` arg used in SDWebImage Core

+1. See the following documentation of AsyncImage.

- https://developer.apple.com/documentation/swiftui/asyncimage/init(url:scale:)
- https://developer.apple.com/documentation/swiftui/asyncimage/init(url:scale:content:placeholder:)
- https://developer.apple.com/documentation/swiftui/asyncimage/init(url:scale:transaction:content:)

**Comment by Kyle-Ye** [comment]
> .context([.imageScale] = 2)

Do you mean using `context: [.imageScaleFactor: 2]` in current init API?

1. `[SDWebImageContextOption : Any]` is using Any so `.imageScaleFactor` can pass a non-number here.

2. Another way is appending `scale = 1` in all WebImage's init. But what if user set both scale and context: [.imageScaleFactor: 2] at the same time?

**Comment by dreampiggy** [comment]
1. `Any` is the only way in Objc API...I already have a plan for SDWebImage 6 which use the `enum associated object` and each key value should be typed.
2. Follow the same design, if the user provided context contains `.imageScale`, then it has the highest priority. Since the the `scale = 1` is default param

**Comment by Kyle-Ye** [comment]
Can we expect a new 3.0.5 or 3.1.0 release?
