### ISSUE TITLE
Removed placeholder - how to replace it

### ISSUE THREAD

**Issue by salvatoreboemia** [SDWebImage/SDWebImageSwiftUI#327]
Hi

how I can replace it?

Thanks

**Comment by dreampiggy** [comment]
Use `content: placeholder:` closure API.

Just like AsyncImage, see Apple's usage

**Comment by dreampiggy** [comment]
https://stackoverflow.com/questions/75088942/adding-a-placeholder-to-asyncimage-and-showing-a-different-image-if-asyncimage-f

**Comment by dreampiggy** [comment]
The readme already contains some example using placeholder via `WebImage`: https://github.com/SDWebImage/SDWebImageSwiftUI?tab=readme-ov-file#using-webimage-to-load-network-image
