### ISSUE TITLE
Adding SDWebImageSwiftUI

### ISSUE THREAD

**Issue by PrivateKodi** [SDWebImage/SDWebImageSwiftUI#328]
Why dose Adding SDWebImageSwiftUI also Add SDWebImage? Could you modify the Swift Package so it won’t add SDWebImage?

**Comment by dreampiggy** [comment]
No, this what this package's used for

**Comment by dreampiggy** [comment]
And SDWebImage 5.x is pure Objective-C framework, which bianry size (in final executable) is 700KB, I don't think it's any issue with it with the features it provides (like Animated Image support for all cases, coder plugin design)
