### ISSUE TITLE
Cant show this picture

### ISSUE THREAD

**Issue by ChildProdigy** [SDWebImage/SDWebImageSwiftUI#335]
http://www.goodnews.org.tw/favicon.ico

I see that the data is loaded correctly but not displayed. 
It should be a problem with IOS itself, 
because native components also have display problems.

**Comment by dreampiggy** [comment]
> native components also have display problems.

Since SDWebImage use Apple's System framework by default, it's designed behavior.

If you want custom decoding, you can see third-party decoder, see more: https://github.com/SDWebImage/SDWebImage/wiki/Coder-Plugin-List

**Comment by dreampiggy** [comment]
Close for now. If you really want better ICO image file compatibility, search GitHub and use any third-party ICO decoding library instead. It's simple to read a wrapper for most C based decoding library.
