### ISSUE TITLE
Getting Reference to property 'transaction' in closure requires explicit use of 'self' to make capture semantics explicit in ImageManager

### ISSUE THREAD

**Issue by softmastx** [SDWebImage/SDWebImageSwiftUI#339]
<img width="963" alt="Screenshot 2567-11-04 at 14 32 36" src="https://github.com/user-attachments/assets/f4f24364-4180-43de-a788-e10e99a5375d">

<img width="685" alt="Screenshot 2567-11-04 at 14 34 57" src="https://github.com/user-attachments/assets/50507315-a8ad-408c-86ce-21b24e5ba7b9">

Xcode 14.2
SDWebImageSwiftUI

**Comment by dreampiggy** [comment]
Seems old version compiler does not support `automatic self capture` ?

**Comment by softmastx** [comment]
<img width="531" alt="Screenshot 2567-11-04 at 15 18 46" src="https://github.com/user-attachments/assets/4527ed1b-7205-4906-a5d7-87398c600384">

It is fixed by replacing `withTransaction(transaction)` with `withTransaction(self.transaction)`

**Comment by dreampiggy** [comment]
If you can compile by fixing this, please submit a PR about this change and I'll merge this.

**Comment by abdullah888** [comment]
I have same problem and I can't solve it

**Comment by dreampiggy** [comment]
@softmastx Hi, can you just submit a PR for this ? It's just one line code.

Since it's so simple I think it's suitable for other developers to contribute

**Comment by softmastx** [comment]
@dreampiggy  I'm working on it.  getting permission error and trying to fix.

**Comment by dreampiggy** [comment]
Closed by #340
