### ISSUE TITLE
Add header to image request

### ISSUE THREAD

**Issue by vipatronon** [SDWebImage/SDWebImageSwiftUI#51]
Is there a way to add a header value to the WebImage component? To get the images from my server, I must pass some info in there

Thanks in advance

**Comment by dreampiggy** [comment]
Already supported and mentioned on Readme: 

> URL Request / Response Modifier, provide custom HTTP Header

See the wiki, you need to pass the context option `.requestModifier`, or you can setup a common header, in the `SDWebImageDownloader.shared`.

Wiki : https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#use-request-modifier-50

I don't want to add many code sample or details in readme, since it's for beginner and quick guide for a framework. For details, the docuementation and wikis is always the better place to check.

**Comment by dreampiggy** [comment]
You can also just use another API, but this will apply to all image request, and does not support a block-based API (Which means, it's static, not dynamic). But it's simpler:

https://sdwebimage.github.io/Classes/SDWebImageDownloader.html#/c:objc(cs)SDWebImageDownloader(im)setValue:forHTTPHeaderField:

**Comment by vipatronon** [comment]
The wiki exemple worked perfectly!

Thank you!

**Comment by dreampiggy** [comment]
@vipatronon I update the readme with a new chapter called **Customization and configuration setup**, make it easier for new user to find the place to do something setup about HTTP headers, coder plugins. Hope this can help for you.

https://github.com/SDWebImage/SDWebImageSwiftUI#customization-and-configuration-setup

**Comment by vipatronon** [comment]
@dreampiggy thank you for updating the readme, I helped me for sure and I think this will help new users too

**Comment by LilaQ** [comment]
@dreampiggy I still don't get it. How can you add a header for a single request? Where / how do you passt the requestModifier for a single request? 
All I can see is changing default headers.

**Comment by dreampiggy** [comment]
Since SD pass you a `URLRequest` value, you can return back another `URLRequest`.

`URLRequest` (actually the mutable one) has a property called `allHTTPHeaderFields`

You know how to use... Though this API not really convenient for simple use case. You can wrap it into a category for convenient

**Comment by dreampiggy** [comment]
```swift
let requestModifier = SDWebImageDownloaderRequestModifier { (request) -> URLRequest? in
    if (request.url?.host == "foo") {
        var mutableRequest = request
        mutableRequest.setValue("foo=bar", forHTTPHeaderField: "Cookie")
        return mutableRequest
    }
    return request
};
imageView.sd_setImage(with: url, options: [], context: [.requestModifier] = requestModifier]) { }
```

**Comment by LilaQ** [comment]
Thank you so much, this clears it up a lot for me! :)

**Comment by dreampiggy** [comment]
There may be a chance for SD to provide better convenient for common Swift users. And this repo can be merged into SDWebImage Core repo (current Objective-C only)

I've have a plan (and demo in (dreampiggy/SDWebImage/swift fork branch)[https://github.com/SDWebImage/SDWebImage/compare/master...dreampiggy:SDWebImage:swift]) to make SDWebImage 6.0 become Swift-Objc-mixed and provide massive better support like enum-associated-object/concurrency/result type, etc). But seems has no extra time to push it recently..
