### ISSUE TITLE
版本0.8.3，运行时崩溃

### ISSUE THREAD

**Issue by dengchaojie** [SDWebImage/SDWebImageSwiftUI#55]
pod 'SDWebImageSwiftUI', '0.8.3'

dyld: lazy symbol binding failed: Symbol not found: _$s17SDWebImageSwiftUI03WebB0V3url7options7contextAC10Foundation3URLVSg_So0aB7OptionsVSDySo0aB13ContextOptionaypGSgtcfC
  Referenced from: /Users/hrt03/Library/Developer/CoreSimulator/Devices/31BE0B65-0320-4B24-A665-0D4FBE827B32/data/Containers/Bundle/Application/472E6385-E16C-4C67-80AE-7B4B52AA06D8/DemoSDWebImage.app/DemoSDWebImage
  Expected in: /Users/hrt03/Library/Developer/CoreSimulator/Devices/31BE0B65-0320-4B24-A665-0D4FBE827B32/data/Containers/Bundle/Application/472E6385-E16C-4C67-80AE-7B4B52AA06D8/DemoSDWebImage.app/Frameworks/SDWebImageSwiftUI.framework/SDWebImageSwiftUI

dyld: Symbol not found: _$s17SDWebImageSwiftUI03WebB0V3url7options7contextAC10Foundation3URLVSg_So0aB7OptionsVSDySo0aB13ContextOptionaypGSgtcfC
  Referenced from: /Users/hrt03/Library/Developer/CoreSimulator/Devices/31BE0B65-0320-4B24-A665-0D4FBE827B32/data/Containers/Bundle/Application/472E6385-E16C-4C67-80AE-7B4B52AA06D8/DemoSDWebImage.app/DemoSDWebImage
  Expected in: /Users/hrt03/Library/Developer/CoreSimulator/Devices/31BE0B65-0320-4B24-A665-0D4FBE827B32/data/Containers/Bundle/Application/472E6385-E16C-4C67-80AE-7B4B52AA06D8/DemoSDWebImage.app/Frameworks/SDWebImageSwiftUI.framework/SDWebImageSwiftUI
https://github.com/dengchaojie/demos/tree/master/Lib/DemoSDWebImage

**Comment by dreampiggy** [comment]
Please demangle the Swift symbol by yourself next time :)

This symbol
` SDWebImageSwiftUI.WebImage.init(url: Foundation.URL?, options: __C.SDWebImageOptions, context: [__C.SDWebImageContextOption : Any]?) -> SDWebImageSwiftUI.WebImage`

should exist. This is the `WebImage` initializer.

What's your Xcode version, iOS firmware version, SDWebImage dependency version, all any environment related to this ?

**Comment by dreampiggy** [comment]
I can not reproduce this issue. Maybe something about your environment ? Try to clean all the Pods cache, deintegrate and reinstall again ?

![image](https://user-images.githubusercontent.com/6919743/68862334-38b9ac00-0728-11ea-9cdb-4ca2300466ca.png)

**Comment by dreampiggy** [comment]
Seems un-reproducable. And I try the CocoaPods all install ways, it all works. So for now, I just close this issue. If you still have the problem, attach your local environment:

+ macOS version
+ Xcode version
+ CocoaPods version
+ and `pod env` output
