### ISSUE TITLE
can not  show  when webimage in navigationlink  

### ISSUE THREAD

**Issue by IMCharles1102** [SDWebImage/SDWebImageSwiftUI#57]
when code is just like that the webimage can show:

```swift
WebImage(url: URL.initPercent(string: "http://gw.alicdn.com/bao/uploaded/i4/1689254167/O1CN01hEMO7G1geWyDWwEjS_!!0-item_pic.jpg")) 
                        .resizable()
                        .placeholder {
                            Image("goods")
                    }
                    .indicator(.activity)
                    .transition(.fade)
                    .frame(width: 80, height: 80, alignment: .center)
                    .aspectRatio(contentMode: .fit)
```

but when this it can not show :

```swift
NavigationLink(destination: DetailView(goodsLink: "ssss", income: "9999")) {
                            WebImage(url: URL(string:"http://gw.alicdn.com/bao/uploaded/i4/1689254167/O1CN01hEMO7G1geWyDWwEjS_!!0-item_pic.jpg")
                                     )
                                .onSuccess { image, cacheType in
                            }
                                .resizable()
                                .placeholder {
                                    Image("goods")
                            }
                            .indicator(.activity)
                            .transition(.fade)
                            .frame(width: 80, height: 80, alignment: .center)
                            .aspectRatio(contentMode: .fit)
                    }
```

**Comment by dreampiggy** [comment]
I can not get your use case. Actually.

NavigationLink's `label: @ViewBuilder()` arg, it used for create a View that place into the current link position. When you click the `label()` view, it will navigate to your target.

So, most of cases, the `label()` arg is a label, or custom View with gesture.

I test your code, it seems SwiftUI use a grey forground `SwiftUI.Button` to cover your image, so it does not show at all.

But with even a simple `Swift.Image`, it can not do what you want. See the code, and the preview.

![image](https://user-images.githubusercontent.com/6919743/68915754-5fb2c500-079e-11ea-8219-382e2f511b77.png)

![image](https://user-images.githubusercontent.com/6919743/68915866-b6200380-079e-11ea-8db1-96054d077dbe.png)

See that `SwiftUI.Image` can do not the thing. So do we. This `WebImage` is most compatible with the SwiftUI's layout and animation system, if `SwfitUI.Image` can not, it can not either.

**Comment by dreampiggy** [comment]
Check: https://www.hackingwithswift.com/quick-start/swiftui/how-to-disable-the-overlay-color-for-images-inside-button-and-navigationlink

If you want to use custom View inside `NaviagtionLink`, you should override the ButtonStyle. By default, the button style is `.default` and will become gray to cover your target.

Use the code:

```
NavigationLink(destination: DetailView(goodsLink: "ssss", income: "9999")) {
                            WebImage(url: URL(string:"http://gw.alicdn.com/bao/uploaded/i4/1689254167/O1CN01hEMO7G1geWyDWwEjS_!!0-item_pic.jpg")
                                     )
                                .onSuccess { image, cacheType in
                            }
                                .resizable()
                                .placeholder {
                                    Image("goods")
                            }
                            .indicator(.activity)
                            .transition(.fade)
                            .frame(width: 80, height: 80, alignment: .center)
                            .aspectRatio(contentMode: .fit)
                    }
.buttonStyle(PlainButtonStyle())
```

**Comment by dreampiggy** [comment]
And I don't see any `NavigationView`, did you implements that from your self ?
By default, if there are no any `NavigationView` wrapped, `SwiftUI.NavigationLink` does not do anything. Check SwiftUI toturial for details.

**Comment by IMCharles1102** [comment]
> Check: https://www.hackingwithswift.com/quick-start/swiftui/how-to-disable-the-overlay-color-for-images-inside-button-and-navigationlink
> 
> If you want to use custom View inside `NaviagtionLink`, you should override the ButtonStyle. By default, the button style is `.default` and will become gray to cover your target.
> 
> Use the code:
> 
> ```swift
> NavigationLink(destination: DetailView(goodsLink: "ssss", income: "9999")) {
>                             WebImage(url: URL(string:"http://gw.alicdn.com/bao/uploaded/i4/1689254167/O1CN01hEMO7G1geWyDWwEjS_!!0-item_pic.jpg")
>                                      )
>                                 .onSuccess { image, cacheType in
>                             }
>                                 .resizable()
>                                 .placeholder {
>                                     Image("goods")
>                             }
>                             .indicator(.activity)
>                             .transition(.fade)
>                             .frame(width: 80, height: 80, alignment: .center)
>                             .aspectRatio(contentMode: .fit)
>                     }
> .buttonStyle(PlainButtonStyle())
> ```

thank you!! it works
