### ISSUE TITLE
Error: Could not build Objective-C module 'SDWebImageSwiftUI'

### ISSUE THREAD

**Issue by Jlively22** [SDWebImage/SDWebImageSwiftUI#63]
[Followed stackoverflow steps to resolve similar issue](https://stackoverflow.com/questions/41709912/error-could-not-build-objective-c-module-firebase)

When building (⌘ + B) I received 36 issues within SDWebImageSwiftUI.

[Build Errors.txt](https://github.com/SDWebImage/SDWebImageSwiftUI/files/3882561/Build.Errors.txt)

**Comment by dreampiggy** [comment]
Are you using the latest version (0.8.6) ? And your install package mangaer ?

+ CocoaPods
+ Carthage
+ SwiftPM

**Comment by dreampiggy** [comment]
I tried all the 3 ways to install this package. Nothing wrong herer. Is this related to your local Xcode build cache ?

Try:
+ Goto `~/Library/Developer/Xcode/DerivedData`
+ Delete all things
+ Restart Xcode
+ Rebuild ?

**Comment by Jlively22** [comment]
@dreampiggy PODS:
- SDWebImage (5.3.2):
- SDWebImage/Core (= 5.3.2)
- SDWebImage/Core (5.3.2)
- SDWebImageSwiftUI (0.8.6):
- SDWebImage (~> 5.3)

I have deleted all folders within Derived Data, restarted Xcode and Rebuilt before posting the issue. Tried again and still have the Buildtime errors.

**Comment by dreampiggy** [comment]
@Jlively22 Don't you use the `use_frameworks!`, or don't you use `modular_headers => true` ? If you want to mixed Objective-C/Swift code, you have to build module, but not raw C header+lib format.

**Comment by dreampiggy** [comment]
See Podfile here in our demo: https://github.com/SDWebImage/SDWebImageSwiftUI/blob/master/Example/Podfile

And the readme about this in SDWebImage's readme: 
https://github.com/SDWebImage/SDWebImage#swift-and-static-framework

**Comment by dreampiggy** [comment]
Or could you please, show me your Podfile, or anything example to re-produce this issue. Sounds a little strange.

**Comment by Jlively22** [comment]
@dreampiggy here is my pod file. Still getting the build errors after commenting taking out use_frameworks!

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for TestApp
source 'https://github.com/CocoaPods/Specs.git'
pod 'SDWebImageSwiftUI'

end

**Comment by dreampiggy** [comment]
Use this re-created demo ? I have no issue at all. With that `use_modular_headers!`.

[TestApp.zip](https://github.com/SDWebImage/SDWebImageSwiftUI/files/3882629/TestApp.zip)

<img width="1680" alt="截屏2019-11-23下午11 38 26" src="https://user-images.githubusercontent.com/6919743/69481233-76b28080-0e4a-11ea-9d9d-6fbda8c16007.png">

**Comment by dreampiggy** [comment]
I guess you're using a out-of-date Xcode 11 beta version. The `ObservableObject` previouslly called `ObjectBinding` protocol. But it already been removed 4 month ago.

We only support the release version of Xcode 11. Currrent latest version is Xcode 11.2.

**Comment by Jlively22** [comment]
I think you're right - Version 11.0 beta (11M336w)

Updating to Xcode 11.2.1. Thanks!
