### ISSUE TITLE
'WebImage' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by ozumado** [SDWebImage/SDWebImageSwiftUI#68]
Hello there,

Recently I started to see this error
`'WebImage' cannot be constructed because it has no accessible initializers`
The project does compile properly but its annoying the error is here all the time.

**Comment by dreampiggy** [comment]
The initializer is `public init(url: URL?, options: SDWebImageOptions = [], context: [SDWebImageContextOption : Any]? = nil)`. See documentation and code.

What does you mean the `no accessible initializers` ?

**Comment by dreampiggy** [comment]
And, could you try the latest version https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/0.10.0 as well ? Or providing me a demo to reproduce this issue,

**Comment by ozumado** [comment]
Thank You for the fast response.
I've been using this package for few days already and didn't have any problem at all, yesterday it started to throw this error, the funny thing is it does compile and work as intended.

![Screenshot 2019-12-6 o 17 28 33](https://user-images.githubusercontent.com/9369622/70338820-e6af0680-184d-11ea-8036-16f762dede80.png)

**Comment by ozumado** [comment]
And yes, I'm currently at the most recent versions 0.10.0 and 5.4.0.

**Comment by dreampiggy** [comment]
> And yes, I'm currently at the most recent versions 0.10.0 and 5.4.0.

Did you try to clear all the DerivedData (`~/Library/Developer/Xcode/DerivedData/`) ?
Then restart Xcode to see the result.

Or, does the version 0.9.0, 0.8.x version contains the same strange warning ?

**Comment by ozumado** [comment]
> Did you try to clear all the DerivedData (~/Library/Developer/Xcode/DerivedData/) ?
> Then restart Xcode to see the result.

Looks like this fixed my problem, sorry to bother you with such a silly issue.

**Comment by dreampiggy** [comment]
:) It's OK...
