### ISSUE TITLE
How to make Image circle? 

### ISSUE THREAD

**Issue by phuongphally** [SDWebImage/SDWebImageSwiftUI#69]

**Comment by dreampiggy** [comment]
Could you please explain whay you means  for `Image Circle` ? I can not get the point.

If you means the Image View Circle clip, you can already use the mask, or corner radius to clicp any SwiftUI View to become a Circle avatar. Check Apple’s SwiftUI toturial for this.

If you mean custom transformer to clip original image to a circle, use SDWebImageCornerRadiusTransformer, which may suit for this task

**Comment by phuongphally** [comment]
@dreampiggy I means the Image View Circle clip. Because I'm new to Swift and IOS , now I solve to 

```swift
            WebImage(url: URL(string:  url)!)
               .onSuccess { image, cacheType in
                   // Success
               }
               .resizable() // Resizable like SwiftUI.Image
               .placeholder(Image(systemName: "photo")) // Placeholder Image
               // Supports ViewBuilder as well
               .placeholder {
                   Rectangle().foregroundColor(.gray)
               }
               .animated() // Supports Animated Image
               .indicator(.activity) // Activity Indicator
               .animation(.easeInOut(duration: 0.5)) // Animation Duration
               .transition(.fade) // Fade Transition
               .scaledToFit()
               .clipShape(Circle())
               .shadow(radius: 10)
               .frame(width: 50, height: 50, alignment: .center)

```

**Comment by dreampiggy** [comment]
Yes. WebImage is just a normal SwiftUI view and compatible for all SwiftUI layout system.

Seems you already solve the issue ? Close this ?
