### ISSUE TITLE
WebImage can not use Custom SDWebImageManager

### ISSUE THREAD

**Issue by takep2** [SDWebImage/SDWebImageSwiftUI#70]
I want to use `WebImage` with Firebase Storage API.
For that, `WebImage` needs to be able to use Custom SDWebImageManager with modified loader.

In the `sd_internalSetImageWithURL` method of SDWebImage, the following code is used to use Custom SDWebImageManager set in the context.
```
        SDWebImageManager *manager = context[SDWebImageContextCustomManager];
        if (!manager) {
            manager = [SDWebImageManager sharedManager];
        }
```

However, `ImageManager` of SDWebImageSwiftUI always uses the default SDWebImageManager by the following code.
```
var manager = SDWebImageManager.shared
```
I hope to add the following code to the `load` method in the `ImageManager` so that the manager set in the context can be used.
```
        if let customManager = context?[.customManager] as? SDWebImageManager {
            manager = customManager
        }
```

**Comment by dreampiggy** [comment]
Sounds a designed changes. Maybe this means, we should use the context option's manager instead always the shared one.

It's not hard to implements, PR is welcomed, or please wait me for days of Spring Festival, thanks ~

**Comment by dreampiggy** [comment]
@takep2 For Firbase URL, have you ever tried the `SDImageLoadersManager` ?

Which implements a multiple loader system, means:

```swift
SDImageLoadersManager.shared.loaders = [SDWebImageDownloader.shared, FirebaseUI.ImageLoader.shared]
```

**Comment by takep2** [comment]
Thank you for the great advice!

I did not know that the default loader of SDWebImageManager could be replaced later.

Based on this advice, I was able to list images using WebImage loaded by Firebase Storage API as the following code.

```
import SwiftUI
import Firebase
import FirebaseUI
import SDWebImageSwiftUI

struct ContentView: View {
    @State var postArray: [PostData] = []
    
    var body: some View {
        List(self.postArray) { (postData) in
            VStack {
                WebImage(url: self.imageURL(postData. imageName)).resizable().indicator(.activity).scaledToFit().frame(minHeight:200)
            }
        }.onAppear() {
            SDWebImageManager.defaultImageLoader = StorageImageLoader.shared
            self.loadData()
        }
    }
    
    func loadData() {
        // loading image names to postArray 
    }
    
    func imageURL(_ imageName: String)->URL {
        let ref = Storage.storage().reference().child("images").child(imageName)
        let url = NSURL.sd_URL(with: ref)! as URL
        return url
    }
```


The problem was solved very simply.

Thanks for providing a great library!

**Comment by dreampiggy** [comment]
This may solve the problem. however, changning the default loader to a single one (like those FirebaseUI) will cause you can not download any HTTP/HTTPS URL.

So, the better idea, it's to use LoadersManager, which implements a multiple loader system, which means, you can load any of resources at the same time, without check what's URL is:

+ HTTP/HTTPS
+ FTP
+ File(file://)
+ Firebase Storage
+ Photos Assets (Using https://github.com/SDWebImage/SDWebImagePhotosPlugin)

**Comment by dreampiggy** [comment]
@takep2 Version [v0.10.1](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/0.10.1) supports to keep the `.customManager` context option.

But, it's recommend to just try out the v1.0.0-beta version, which provide a stable API (in long-term) and better support for AnimatedImage on WebImage. See more about [v1.0.0 beta release](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/1.0.0-beta)

**Comment by Dwite** [comment]
Hello @dreampiggy, so do you have an example of how it should work? I'm trying to make it work with Firebase "gs://" URLs as they mentioned in https://github.com/firebase/FirebaseUI-iOS/blob/master/Storage/README.md

```
// Use gs:// URL directly with StorageImageLoader
let storageUrl = URL(string: "gs://...")!
```

With simple WebImage as

```
WebImage(url: book.thumbnail)
            .frame(width: 100, height: 100)
```

and configured 

`SDImageLoadersManager.shared.loaders = [SDWebImageDownloader.shared, FirebaseUI.StorageImageLoader.shared]
`

But receive such error

```
Task <22AEFC72-C893-4E2B-9279-572AE567A64D>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=gs://stickerland-smartfox.appspot.com/QIWInaKazhdiyDen/CAACAgIAAxkBAAIWk19SL-_471VlEnz22e-4h-D6CXr7AAK3LAEAAWOLRgyY67_5bQXHLBsE.webp, NSErrorFailingURLKey=gs://stickerland-smartfox.appspot.com/QIWInaKazhdiyDen/CAACAgIAAxkBAAIWk19SL-_471VlEnz22e-4h-D6CXr7AAK3LAEAAWOLRgyY67_5bQXHLBsE.webp, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <22AEFC72-C893-4E2B-9279-572AE567A64D>.<1>"
```

If I make the `FirebaseUI.StorageImageLoader.shared` as default loader the is no error, but also no image is shown

**Comment by dreampiggy** [comment]
@Dwite Your loaders array order is wrong...It's a priority queue. So it should be

```swift
SDImageLoadersManager.shared.loaders = [FirebaseUI.StorageImageLoader.shared SDWebImageDownloader.shared]
```

**Comment by Dwite** [comment]
@dreampiggy even if I change the order, the problem still exists. If I remove the SDWebImageDownloader.shared completely 

```
SDImageLoadersManager.shared.loaders = [FirebaseUI.StorageImageLoader.shared]
SDWebImageManager.defaultImageLoader = SDImageLoadersManager.shared
```

There are no errors in logs, but images won't appear and all `WebImage.onFailure` are called with empty error `domain: nil - code: 0`

**Comment by dreampiggy** [comment]
Can you please provide a demo (and your Firebase Storage URL) for me to test ? Sounds little strange, because the loading system for UIKit or SwiftUI are shared. So it should handle the gs as well. Or the Firebase-Storage Unit Test will fail...

**Comment by Dwite** [comment]
@dreampiggy I have added you as a contributor to my [project](https://github.com/Dwite/Stickerland-iOS), it's almost empty, just the code with the web image + Firebase storage 

Here is an example URL 

`gs://stickerland-smartfox.appspot.com/ChristisRisen_stickers/CAACAgIAAxkBAAIWll9SL_vXzeNSk1NjK8B-XeWWvMECAALcyQEAAWOLRgy0EthwY9D3JRsE.webp`

**Comment by dreampiggy** [comment]
FirebaseStorage UI version wrong :)

The fixed code (which supports raw NSURL, not NSURL created with special API (sd_sd_URLWithStorageReference), already on master: https://github.com/firebase/FirebaseUI-iOS/blob/master/Storage/FirebaseStorageUI/FUIStorageImageLoader.m#L53-L63

However, your example code:

![image](https://user-images.githubusercontent.com/6919743/92574435-a8051b80-f2b9-11ea-98cd-adf5598484f1.png)

**Comment by dreampiggy** [comment]
Seems, FirebaseStorage UI does not release new version which contains those fix code...Need to fire issues to them. I can fire one as well.

**Comment by Dwite** [comment]
@dreampiggy so I should update the Firebase-UI to the new version (I thought 8.0 is the latest) or just create URL with special API for now?

**Comment by dreampiggy** [comment]
You need some super trick code, to create an URL with associated with `StorageReference`...

OC one:

```objective-c
    NSString *bucketUrl = [NSString stringWithFormat:@"gs://%@", url.host];
    FIRStorage *storage = [FIRStorage storageWithURL:bucketUrl];
    storageRef = [storage referenceWithPath:url.path];
    url.sd_storageReference = storageRef;
```

Swift one:

**Comment by dreampiggy** [comment]
I know this not looks well and difficult, so this is why I create PR for Firebase Team to add a better API to supports `gs://` URL built-in. However seems they forgot to release new version. 😢

**Comment by Dwite** [comment]
@dreampiggy and to use `NSURL` for `WebImage` I can just cast it to `URL`, correct?

**Comment by dreampiggy** [comment]
NSURL and URL is bridgable in Swift.

**Comment by Dwite** [comment]
@dreampiggy Sorry for bothering 😢  I have updated with your code sample and now in the logs, it shows

`[NSError init] called; this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.`

I have published the code to the sample project,

The image loaders are currently initing like this

```
SDImageLoadersManager.shared.loaders = [FirebaseUI.StorageImageLoader.shared]
SDWebImageManager.defaultImageLoader = SDImageLoadersManager.shared
```

**Comment by dreampiggy** [comment]
@Dwite FirebaseUI release [v8.5.1](https://github.com/firebase/FirebaseUI-iOS/releases/tag/v8.5.1), which added the built-in support for any "gs://" URL.
You don't need the hack I talked above. This dirty work handled by framework.

**Comment by SnowballAntrobus** [comment]
@dreampiggy hello friend I'm confused about this simple code:

        SDWebImageManager.defaultImageLoader = StorageImageLoader.shared
        let ref = Storage.storage().reference().child(self.imageURL)
        print(ref)
        let url = NSURL.sd_URL(with: ref)! as URL
        return WebImage(url: url)

When I run this I get blank images. If I remove the first line I get a Code=-1002 "unsupported URL" error. Could you please help me?
