### ISSUE TITLE
onSuccess is not executed if already cached

### ISSUE THREAD

**Issue by foolbear** [SDWebImage/SDWebImageSwiftUI#76]
I want get the uiimage of remote and save it to the photo library, onSuccess is a  good solution, but I found that onSuccess is not executed if already cached, I cannot get the uiimage from here every time. Is this a issue or is there another solution for this?

```
WebImage(url: URL(string: "https://nokiatech.github.io/heif/content/images/ski_jump_1440x960.heic"))
        .onSuccess { image, cacheType in
            // Success
            print("\(image), \(cacheType)")
        }
```
and cacheType = SDImageCacheType?
20-02-01 16:11:19 CardView[37], ContentView: <UIImage:0x2830f3060 anonymous {1310, 256}>, SDImageCacheType

**Comment by dreampiggy** [comment]
Seems because of hitting image cache, which is **Sync**. So by the time you access `.onSuccess`, the completionBlock already been called. 😓 

I'll provide a quick fix, to allows async dispatch for manager. Maybe another beta version ?

**Comment by dreampiggy** [comment]
Seems we should not make it async, because SwiftUI may like to create another new Struct when display changes, such as entering the Edit Mode of list.

I'll find the solution soon.

**Comment by foolbear** [comment]
@dreampiggy thanks very much. I using SDWebImageSwiftUI by Swift Package, so I must wait for your next tag.

**Comment by dreampiggy** [comment]
@foolbear Does this test case cover you use case ?
I test this fix the issue. Also, compatible with List Entering Edit Mode. (This is a edge case that SwiftUI create your View struct without calling `onAppears`...)

**Comment by dreampiggy** [comment]
> I using SDWebImageSwiftUI by Swift Package, so I must wait for your next tag.

This is not related to the package manager... For SwiftPM, you can choose to use `Git Tag/Git Branch/Git Commit/ Local` 4 types of dependency.

You can just clone this repo, checkout the branch, then drag the folder into your Xcode Project, Xcode will override the remote dependency with the local one, you can test and debug.

See: https://developer.apple.com/documentation/swift_packages/editing_a_package_dependency_as_a_local_package?language=objc

**Comment by dreampiggy** [comment]
@foolbear If you previouslly use 0.x version (0.10.2 or somthing), I've already released one patch version [v0.10.3](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/0.10.3) for this.

Note on the middle or end of February, I decide to release official 1.0.0 version, which break some of APIs from 0.x and provide a better support for WebImage on animation...

So, currently small patches will pick back to 0.x version, but after 1.0.0 released, no more changes will be applied on 0.x version.

**Comment by foolbear** [comment]
@dreampiggy in v0.10.3, onSuccess executed every time. but warning occurs : "Modifying state during view update, this will cause undefined behavior.", and I cannot get the UIImage. Maybe I use it in a wrong way:

```
import SDWebImageSwiftUI

struct TestImageView: View {
    @State private var uiImageFromRemote: UIImage? = nil
    
    var body: some View {
        VStack {
            WebImage(url: URL(string: "https://avatars0.githubusercontent.com/u/827316?s=88&v=4"))
                .onSuccess { image, cacheType in
                    self.uiImageFromRemote = image
            }
            .resizable()
            .indicator(.activity)
            .transition(.fade)
            .scaledToFit()
            uiImageFromRemote.map { uiimage in
                Button(action: { /*to save uiImageFromRemote to photo library*/ }) {
                    Image(uiImage: uiimage).frame(width: 100, height: 100)
                }
            }
        }
    }
}
```

**Comment by foolbear** [comment]
image for button not shown even adding DispatchQueue.main.async{}.
```
WebImage(url: URL(string: "https://avatars0.githubusercontent.com/u/827316?s=88&v=4"))
                .onSuccess { image, cacheType in
                    DispatchQueue.main.async {
                        self.uiImageFromRemote = image
                    }
            }
```

**Comment by dreampiggy** [comment]
The sample code works well. Do you have something extra config (like WebP?) ? I can not reproduce your problem after that PR #77 was merged.

![image](https://user-images.githubusercontent.com/6919743/73594928-b0d88680-454d-11ea-97e3-7b9845b313b8.png)

**Comment by dreampiggy** [comment]
If you means "I want to update another View based on the onSuccess callback". Sadly, you business SwiftUI code is wrong.

Anything trigger the update value (even the value is same, pay attention), SwiftUI will call your `body` again.

To correct use do what you want, check this sample code:

**Comment by foolbear** [comment]
@dreampiggy roger that and thanks!

**Comment by dreampiggy** [comment]
I'll merge that and release a 1.0.0-beta2 version as well.
