### ISSUE TITLE
Missing required module 'SDWebImage'

### ISSUE THREAD

**Issue by adamayoung** [SDWebImage/SDWebImageSwiftUI#79]
Not sure if this is an SDWebImageSwiftUI/SDWebImage issue, or a Swift Package Manager issue, but when I have an iOS app with an accompanying watchOS app, and include SDWebImageSwiftUI in both the iOS app and watchOS app extension (via SPM), building the watchOS app using the watchOS app scheme succeeds, but when trying to build the iOS app, the watchOS app build fails with an error in the SDWebImageSwiftUI library:

```
No such module 'SDWebImage'
```

If I remove the SDWebImageSwiftUI library from the watchOS app extension, I get an error in the watchOS app extension:

```
Missing required module 'SDWebImage'
```

**Comment by dreampiggy** [comment]
Sounds little strange.

Did you mean: When I create a dependent WatchKit App with SwiftUI (The Host WatchOS App is not gray), this cause the import issue ?

Can you have a quick test with other Package Manager like Carthage and CocoaPods, to test whether SwiftPM cause issues ?

**Comment by dreampiggy** [comment]
And, please do a clean build between you switch Xcode scheme, I doubt this is because some cache issues ?

**Comment by adamayoung** [comment]
Tried the clean build, and deleted the derived data directory, but no joy.

Here's the commit it's happening on

https://github.com/adamayoung/Movies/tree/641d17534a99aab103499103e818eba0fa3fa135

I've created an independent watch app now, and it's working as expected.

**Comment by adamayoung** [comment]
Instructions to reproduce:

* Create new Xcode iOS Project
* Add SDWebImageSwiftUI as a Swift Package dependency and include in iOS target
* import SDWebImageSwiftUI in a file in the iOS target
* Build - should be fine

* Add a new target - 'Watch App for iOS App'
* Link SDWebImageSwiftUI library in watch extension target
* import SDWebImageSwiftUI in a file in the watch extension target
* Build watch scheme - should be fine

* Change back to the iOS app scheme
* Build - Should get error 'No such module 'SDWebImage'

**Comment by dreampiggy** [comment]
Can not reproduce on Xcode 13.1 ? Any extra steps ?

Build - should be fine

Add a new target - 'Watch App for iOS App'

Link SDWebImageSwiftUI library in watch extension target

import SDWebImageSwiftUI in a file in the watch extension target

Build watch scheme - should be fine

Change back to the iOS app scheme

Build Fine for me ---> Build - Should get error 'No such module 'SDWebImage'

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/75027731-07e0d400-54da-11ea-9068-0a347deffc67.png)

![image](https://user-images.githubusercontent.com/6919743/75027747-0dd6b500-54da-11ea-94f2-057a365bca71.png)

**Comment by joeycarmello** [comment]
I also hit this error, but only on the XCode 11.4 Beta.

**Comment by dreampiggy** [comment]
@joeycarmello @adamayoung Does Xcode 11.4 Beta 2 solve this issue ?
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_beta_2_release_notes?language=objc

**Comment by joeycarmello** [comment]
On Xcode 11.4 Beta 2 I get the following while attempting to resolve packages:


```
Source files for target SDWebImageMapKit should be located under DerivedData/[X]/SourcePackages/checkouts/SDWebImage
DerivedData/[X]/SourcePackages/checkouts/SDWebImage/Package.swift: target 'SDWebImageMapKit' referenced in product 'SDWebImageMapKit' is empty
```

**Comment by dreampiggy** [comment]
@joeycarmello @adamayoung 

This issue seems been solved by Xcode 11.4-Beta3.

Check SDWebImage/SDWebImage#2941

**Comment by anoop4real** [comment]
I am getting this issue in XCode 12, tried both SPM as well as Cocoapods. I added a new WatchOS target to my existing iOS app and later on I get the error `No such module 'SDWebImageSwiftUI'`
Both the projects fails to build ... any clue?

**Comment by EricWVGG** [comment]
Afraid I'm seeing this in XCode 13. Note that the project does compile and run correctly; the bug seems to be in `Tests iOS`, and interrupts SwiftUI previews.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/617762/135134084-4906dca5-345a-48c8-860e-02b1b07e6fc4.png">

**Comment by chrishutchinson** [comment]
> Afraid I'm seeing this in XCode 13. Note that the project does compile and run correctly; the bug seems to be in `Tests iOS`, and interrupts SwiftUI previews.
>

I was also struggling with this breaking my SwiftUI previews. I was able to resolve it by ensuring the test target host application was set correctly:

1. Navigate to your Xcode project in the left sidebar
2. Select your "Tests" target
3. In the General tab, under Testing, ensure you have a "Host application" selected

I hope that helps!

**Comment by romrell4** [comment]
> I am getting this issue in XCode 12, tried both SPM as well as Cocoapods. I added a new WatchOS target to my existing iOS app and later on I get the error `No such module 'SDWebImageSwiftUI'` Both the projects fails to build ... any clue?

Did you ever get this figured out? I'm getting this in Xcode 13 as well?

**Comment by NamanVaishnav** [comment]
<img width="675" alt="Screenshot 2022-02-01 at 8 29 53 PM" src="https://user-images.githubusercontent.com/6386216/151992951-d6744646-7ae8-4850-8935-32700203b034.png">


^ doing this I solved the issue

**Comment by ucwealth** [comment]
> <img alt="Screenshot 2022-02-01 at 8 29 53 PM" width="675" src="https://user-images.githubusercontent.com/6386216/151992951-d6744646-7ae8-4850-8935-32700203b034.png">
> 
> ^ if you are getting error in XCTests or XCUITest then select your test targate and perform this

Thanks. This worked for me

**Comment by r10s** [comment]
getting a similar error after a pod update with xcode 14.3.1 as well - from the [diff](https://github.com/deltachat/deltachat-ios/pull/1926), not much was changed, but afterwards i am getting the error **No such module 'SDWebImage'**
