### ISSUE TITLE
can't compile package 

### ISSUE THREAD

**Issue by Veeit** [SDWebImage/SDWebImageSwiftUI#85]
<img width="1743" alt="Screenshot 2020-03-04 at 13 48 19" src="https://user-images.githubusercontent.com/22853176/75881193-e0b1cd00-5e1e-11ea-8a38-4dec98409da7.png">

hey, 

I have the problem that I can't compile the package. I have tested it with Xcode 11.3.1 (11C504)
and Version 11.4 beta 2 (11N123k).

**Comment by dreampiggy** [comment]
Use Xcode 11.4 Beta 3. See #79
