### ISSUE TITLE
can't add a custom header

### ISSUE THREAD

**Issue by mesheilah** [SDWebImage/SDWebImageSwiftUI#99]
I've read [your wiki](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage) on how to set a default header, but the class `SDWebImageDownloader` itself isn't available with `SDWebImageSwiftUI` namespace, or there is maybe some kind of necessary import that I'm not aware of ?
plus, I need to pass a user token with some images but not all images in the app, so it's not going to be a default header set in AppDelegate, but rather a custom header for some cases, I couldn't find a way to a pass a custom header with `SDWebImageSwiftUI`

**Comment by dreampiggy** [comment]
You need :

```swift
import SDWebImageSwiftUI
import SDWebImage
```

The SDWebImageSwiftUI does not have a `@_exported import SDWebImage` to automatically do this, because at that time I think `This framework most common use case should not touch SDWebImage backend`...

Maybe I can added one in 1.3.2 version ? Any idea or PR ?

**Comment by dreampiggy** [comment]
Maybe this can help: #100

**Comment by mesheilah** [comment]
@dreampiggy yeah I thought it was an issue with SwiftPM too. 
However, regarding the custom header thing, is there a way to include it for some images rather than in AppDelegate for all images ?

**Comment by dreampiggy** [comment]
Maybe I don't correctly understand your use case ?

You mean: "Can I choose only use A decoder to this URL, instead of register the coder plugin globally" ?

Use context option `[.imageCoder : SDImageSVGCoder.shared]` solve this.

**Comment by dreampiggy** [comment]
Request Modifier is a powerful tool beyond just HTTP header. You can modify the HTTP Method (for example, HEAD, POST, instead of default GET method), HTTP Body, allowsCellularAccess, allowsExpensiveNetworkAccess for low data mode, etc.

**Comment by mesheilah** [comment]
'Type 'SDWebImageContextOption' has no member 'requestModifier'' error fires.

**Comment by mesheilah** [comment]
it must be `downloadRequestModifier` not `requestModifier` this change makes it compile.

**Comment by dreampiggy** [comment]
Sorry the strange naming :)...In the future this context option will become a Swift enum with associated value.

See more https://github.com/SDWebImage/SDWebImage/issues/2980

**Comment by mesheilah** [comment]
so to wrap up, a simple usage for this option is:
`[.downloadRequestModifier: SDWebImageDownloaderRequestModifier(block: { (request) -> URLRequest? in
                    var request = request
                    request.setValue("MyValue", forHTTPHeaderField: "MyHeader")
                    return request
                })]`

**Comment by dreampiggy** [comment]
Yes. Use Swift closure syntax can simply to

```swift
[.downloadRequestModifier: SDWebImageDownloaderRequestModifier {
    var request = $0
    request.setValue("MyValue", forHTTPHeaderField: "MyHeader")
    return request
}]
```


The request modifier is powerful, and can be reused. So this is why it design like that.

Maybe can have a single convience one like `.HTTPHeader : ["Foo" : "bar"]` which translate to this in future Swift API.

**Comment by dreampiggy** [comment]
@mesheilah [1.3.2](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/1.3.2) version released. Please upgrade, so that you don't need to manually import SDWebImage.

**Comment by dreampiggy** [comment]
@mesheilah  SDWebImage 5.8.0 released. Which added the convenient API for HTTP header request/response modifier. See full changelog: https://github.com/SDWebImage/SDWebImage/releases/tag/5.8.0
